docs/devices.md, docs/devices/mk220.txt, docs/usb-ids.txt, lib/logitech_receiver/base_usb.py, packaging/debian/solaar.udev, rules.d/42-logitech-unify-permissions.rules
The MK220 receiver has usbid 046d:c52e, adding this id as a generic
receiver is enough to show the mouse and keyboard charge status.
=> Add support for MK220 mouse-keyboard combo device.

lib/logitech_receiver/descriptors.py
I own the former and wanted to correct this detail which caused the wrong
model to be shown in GUI.
Signed-off-by: Stephen Lyons <slysven@virginmedia.com>
This addresses my Issue #255
=> add: wpid for M 175 to distinguish between it and M185 wireless mouse

lib/solaar/ui/__init__.py
The main window suddenly opening when a battery is critical is very disruptive. It can pop up on all sort of undesirable scenarios, and isn't really a sane behaviour. Rather than catch users of guard, merely show a notification to notify users that the battery is critical.
Fixes #231
=> Don't open a main window when battery is critical

docs/devices.md, lib/logitech_receiver/descriptors.py
Solaar is working with the nano receiver, battery info showing just missing the description about the mouse. This adds the MX 1100 to the list.
=> Adding Logitech mx 1100 cordless laser mouse to discriptors

lib/solaar/ui/tray.py
PyGIWarning: AppIndicator3 was imported without specifying a version
first. Use gi.require_version('AppIndicator3', '0.1') before import to
ensure that the right version gets loaded.
=> Fix: "AppIndicator3 was imported without specifying a version first"

docs/debian.md
Github Pages support HTTPS natively, so it's better for security to default to that.
=> Use HTTPS for github based repositories

bin/solaar
Python 2 needs utf-8 decode since it uses 'ascii' decode by default.
Fixes #291 
```
$ python --version ; echo ; bin/solaar show
Python 2.7.12
File "bin/solaar", line 42, in <module>
init_paths()
File "bin/solaar", line 29, in init_paths
prefix = _path.normpath(_path.join(_path.realpath(sys.path[0]), '..'))
File "/usr/lib/python2.7/posixpath.py", line 73, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
```
```
$ python --version ; echo ; bin/solaar show
Python 3.5.2
solaar: error: Logitech receiver not found
```
```
$ python --version ; echo ; bin/solaar show
Python 2.7.12
solaar: error: Logitech receiver not found
```
```
$ python --version ; echo ; bin/solaar show
Python 3.5.2 …
```
=> UTF-8 file paths error on python 2

docs/devices.md, docs/devices/anywhere-mx-2.txt, lib/logitech_receiver/descriptors.py
Information from mouse Anywhere MX 2 as provided by @fropeter
Descriptor for mouse based on dump provided.
ToDo: Debug smooth scrolling since @fropter reported error reading this property.
relates to #283 
=> Anywhere MX 2 device information and descriptor

docs/i18n.md, lib/logitech_receiver/i18n.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/status.py, lib/solaar/ui/about.py, lib/solaar/ui/pair_window.py, lib/solaar/ui/window.py, po/ru.po, po/solaar.pot, share/applications/solaar.desktop
I think there is some work needed in Solar for better localization. You need to use [gettext.ngettext](http://docs.python.org/3/library/gettext.html#gettext.ngettext) function for plural forms and do _NOT_ concatenate strings like this:
<pre>
_UNIFYING_RECEIVER_TEXT = (
gettext.ngettext("No device paired") + '.\n\n<small>' + _("Up to %d devices can be paired to this receiver") + '.</small>',
'%d ' + _("paired devices") + '\n\n<small>' + _("Up to %d devices can be paired to this receiver") + '.</small>',
</pre>
Instead write something like this:
<pre>
_UNIFYING_RECEIVER_TEXT = (
_("No device paired.\n\n<small>"Up to %d devices can be paired to this receiver.</small>",
_("%d paired devices.\n\n<small>Up to %d devices can be paired to this receiver.</small>",
</pre>
See …
=> Russian translation added.

docs/devices.md, docs/devices/k270-unifying.txt, lib/logitech_receiver/descriptors.py
Descriptor and docs for K270 (unifying version).
=> Wireless Keyboard K270 unifying

lib/logitech_receiver/descriptors.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/settings_templates.py, lib/solaar/cli/show.py
Add support for controlling and events for the MX Anyware 2 High-res Wheel
The high-res wheel allows setting 3 properties:
- if the wheel will scroll inverted;
- if the wheel will use high-resolution (e. g. will scroll faster);
- if the wheel will send HID++ or HID notifications.
Currently, the Logitech HID Kernel driver doesn't handle HID++ wheel notifications. So, when this mode is set, the scroll won't work on apps. It is possible to see the HID++ messages, though, by enabling solaar debug logs.
With this mouse, mouse movement and wheel HID events, on HID mode are like those:
<pre>
000009159 ms 000008 ms (007961 us EP=83, Dev=6a) >>> 20 03 02 00 00 ff ff ff 00 00 00 00 00 00 00
000009167 ms 000008 ms (007957 us EP=83, Dev=6a) >>> 20 03 02 00 00 00 f0 ff 00 00 00 00 00 00 00
000009175 …
=> Mx anywhere2 v5

docs/devices/M510_HIDppV4.5.txt, lib/logitech_receiver/descriptors.py
*** Depends on #337
fixes #279
Smooth Scrolling feature is set but as result it diverts events to HID++ instead of HID. As result, since Logitech Kernel Driver does not handle these events, wheel stops to work. This is not Solaar bug.
Pointer Speed works thanks to @doctor64 work.
=> Add M510 (new version) to descriptors

docs/installation.md
Add '-a' after gpasswd to add USER to group plugdev.
Per: ➜ gpasswd --help
Usage: gpasswd [option] GROUP
Options:
-a, --add USER                add USER to GROUP
-d, --delete USER             remove USER from GROUP
-h, --help                    display this help message and exit
-Q, --root CHROOT_DIR         directory to chroot into
-r, --remove-password         remove the GROUP's password
-R, --restrict                restrict access to GROUP to its members
-M, --members USER,...        set the list of members of GROUP
-A, --administrators ADMIN,...
set the list of administrators for GROUP
Except for the -A and -M options, the options cannot be combined.
=> Minor installation.md edit; gpasswd cmd

README.md
The "Fedora Package DB" is not updated any more, refer to the new "Fedora Packages" instead.
=> Update link to Fedora package in README.md

lib/logitech_receiver/descriptors.py
Add descriptor for MX Master 2S to support High Resolution Wheel, correct charge level and DPI configuration
=> Add MX Master 2S descriptor

lib/solaar/ui/window.py
Other Tree Views in Gnome 3 have borders, so I added a border to Solaar's UI to match.
=> Added border around tree view.

docs/devices/m235.txt
The info was fetched from the command `solaar show`, the version of solaar was the latest commit: 932164458a310f9c11afd81c2ed6b04fbd5b605c
I only replace the real serial number with `00000000` to hide the sensitive info.
=> docs/devices: Add m235 device information

docs/debian.md
Solaar is available on official Debian repository and the old repo link `https://pwr.github.io/Solaar/packages/` is dead and causes `404  Not Found` error and `The repository 'http://pwr.github.io/Solaar/packages ./ Release' does not have a Release file.` error when doing `apt update` so I updated the installation instructions.
=> Update of the installation instructions for Debian

lib/logitech_receiver/descriptors.py
Add the same settings to the logitech MX Master as the one from the MX
Master 2 (scroll wheel DPI, smart scoll sensitivity).
Tested on Ubuntu 18.04
=> Add MX Master settings to descriptors

lib/logitech_receiver/i18n.py, lib/logitech_receiver/status.py, lib/solaar/i18n.py, lib/solaar/ui/window.py
Similar to [what's done for `gettext`](https://github.com/pwr/Solaar/blob/0.9.2/lib/solaar/i18n.py#L62) but for `ngettext`.
Without this change,  errors like the following occur with the French locale (and maybe others) using python2:
```
File "/home/patrick/workspaces/Solaar/lib/solaar/ui/window.py", line 382, in _device_selected
_update_info_panel(device, full=True)
File "/home/patrick/workspaces/Solaar/lib/solaar/ui/window.py", line 697, in _update_info_panel
_update_receiver_panel(device, _info._receiver, _info._buttons, full)
File "/home/patrick/workspaces/Solaar/lib/solaar/ui/window.py", line 574, in _update_receiver_panel
paired_text += '\n\n<small>%s</small>' % ngettext('Up to %(max_count)s device can be paired to this receiver.', 'Up to …
```
=> Fix UnicodeDecodeError with ngettext and python2

lib/logitech_receiver/base_usb.py, packaging/debian/solaar.udev, rules.d/42-logitech-unify-permissions.rules
I've added vid:pid of Lenovo dongle and it seems to work just fine.
Lenovo N50 mouse is recognised as M185/M225.
```shell
$ solaar show
Unifying Receiver
Device path  : /dev/hidraw1
USB id       : 046d:6042
Serial       : F33D96C3
Firmware   : 22.11.B0007
Has 1 paired device(s) out of a maximum of 1.
Notifications: wireless, software present (0x000900)
1: Wireless Mouse M185/M225
Codename     : M185/M225
Kind         : mouse
Wireless PID : 4029
Protocol     : HID++ 2.0
Polling rate : 8 ms (125Hz)
Serial number: 0320E001
Firmware: RQM 27.02.B0028
The power switch is located on the base.
Supports 13 HID++ 2.0 features:
0: ROOT                   {0000}   
1: FEATURE SET            {0001}   
2: DEVICE FW VERSION      {0003}   
3: DEVICE NAME            {0005}   
4: BATTERY STATUS …
```
=> Added basic support for Lenovo dongle

lib/logitech_receiver/base_usb.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py, rules.d/42-logitech-unify-permissions.rules
I was waiting for the migration to send this patch but since it has been put on hold, here it is.
=> base-usb: add support for Lightspeed receivers

lib/hidapi/udev.py, lib/logitech_receiver/receiver.py
I found the cause for not being able to detect receivers sometimes.
It was related to error out when SIGPIPE is fired during the write inside the hidapi.
I've created a loop with retrycount and catching EPIPE and trying the write 3 times.
I tested it as well with just ignoring EPIPE, which is working too, but has the drawback, that the read loop inside the base.request has to time out once.
=> fix: #531 #537. Better handling of EPIPE during hid write.

lib/solaar/ui/about.py, packaging/debian/control, packaging/gentoo/solaar-0.8.8.1.ebuild, setup.py
After repo transfered to pwr-solaar(#407), github.io link url also changed. 
Signed-off-by: Daehyeok Mun <daehyeok@google.com>
=> Fix broken github.io link to new repo url

lib/solaar/ui/icons.py
It was previously assigning levels 1-89 to caution and 90+ to full, which was unintended due to the floor division by 100
=> Fix mint(symbolic) icon theme battery level

lib/logitech_receiver/settings_templates.py
This addresses #544.
Previous output from `solaar -dd`:
```
File "/home/chad/Documents/Solaar/lib/logitech_receiver/listener.py", line 185, in run
self._notifications_callback(n)
File "/home/chad/Documents/Solaar/lib/solaar/listener.py", line 213, in _notifications_handler
configuration.attach_to(dev)
File "/home/chad/Documents/Solaar/lib/solaar/configuration.py", line 130, in attach_to
for s in device.settings:
File "/home/chad/Documents/Solaar/lib/logitech_receiver/receiver.py", line 254, in settings
_check_feature_settings(self, self._settings)
File "/home/chad/Documents/Solaar/lib/logitech_receiver/settings_templates.py", line 385, in check_feature_settings
check_feature(_SMOOTH_SCROLL[0], _F.LOWRES_WHEEL)
File …
```
=> Repair low resolution smooth scrolling

docs/devices/mx-master-2s.txt
Added an information text file with the show command data about the MX Master 2s mouse. The source of this information is: https://github.com/pwr-Solaar/Solaar/issues/595.
=> docs: devices: add MX Master 2s

setup.py
Installation from source sometimes fails with userwarning unknown distribution option.
I have found a solution that works for me. See: https://stackoverflow.com/questions/9810603/adding-install-requires-to-setup-py-when-making-a-python-package a
=> Installation from source sometimes fails with userwarning

lib/logitech_receiver/descriptors.py
change wpid 4055 in descriptors.py to be a new M310 (styled like the new M185)
This is to fix https://github.com/pwr-Solaar/Solaar/issues/609
=> change 4055 to new M310

COPYRIGHT, packaging/debian/copyright
These changes clear up some licensing issues.
Initial issue  https://github.com/pwr-Solaar/Solaar/issues/178
Newer issue https://github.com/pwr-Solaar/Solaar/issues/615
Should there be a new upstream contact in the debian copyright file?
Should Daniel Pavel be contacted for approval?
=> clarify license status; fix debian packaging copyight notice

lib/solaar/ui/window.py
The solaar window is set up to always be on top.  This can be very distracting.  It is also not needed as the window can always be shown by clicking on a receiver or device in the tray menu.
Closes #617
=> don't have window always be on top

lib/logitech_receiver/base.py
Don't produce debugging message for normal HID reports for things like mouse motion and key presses.  Right now this eliminates the debug message for any report less than 0x10, which are precisely the reports that currently generate the debugging message.
Address issues #621
=> don't produce debugging message for normal device HID reports

lib/solaar/cli/show.py
This commit fixes the error I see when showing HID++ 1.0 mice.
I tried to keep the logic as close as possible to the change in the previous commit, but it seems to me that it would be better to have something like:
- if there is voltage information, show it
- otherwise show battery information (2.0 or 1.0)
- otherwise punt
This addresses #633
=> hidpp20: fix error when showing battery

lib/solaar/ui/window.py
Offline devices should not be counted when determining whether a receiver has open slots to pair in.
This PR replaces #631 but has the same changes is that PR does.
=> fix sensitivity of Pair new device button

lib/solaar/ui/window.py
Don't force two column widths to 1 pixel in tree view.
Fixes crash when theme adds padding.
Also slightly improves window layout.
Also adds solaar style class to main window.
Fix #578
Fix #644
=> ui: fix crash when realizing main window in some themes; show icons in tree view

lib/logitech_receiver/descriptors.py, lib/logitech_receiver/settings.py, lib/solaar/configuration.py
Solaar attaches the saved device settings to each individual setting, but this is not done for features discovered at run time.  This patch moves the saved device settings from the individual settings to the device itself, which is, I think, a better place for them.  Individual settings then get the saved device settings from the device and also store changes there.
Fixes #551
=> fix problem with Solaar not applying saved settings for features discovered at run time

lib/solaar/gtk.py, lib/solaar/ui/__init__.py, lib/solaar/ui/window.py, setup.py, share/applications/autostart/solaar.desktop
So 
solaar
will start with the window visible (this is a change)
and
solaar -tray
will start with only the icon in the tray.
Documentation has not yet been updated - waiting for my other documentation changes to be pulled so that I don't have to merge changes.  
Update: Documentation update may not be necessary --help provides information
=> add --tray option to start without window visible

lib/logitech_receiver/receiver.py, lib/solaar/cli/__init__.py
This only fixes the error caused by using an integer for the serial number of c534.
It does not fix the number of pairable devices.  That needs more of my earlier changes for the c534, which are waiting for information from Logitech.
Addresses #636
=> receiver: use None for serial number of c534

bin/solaar, setup.py
Force use of python3 in solaar and setup.py
=> solaar: use python3, not generic python

bin/solaar, bin/solaar-cli, lib/solaar/gtk.py, lib/solaar/tasks.py, packaging/debian/control, setup.py, tools/hidconsole
As an outcome of issues #652 and #653 , looks like Solaar does not support python2 anymore at least under Debian/Ubuntu and their derivatives. 
The following pull request updates python version. There are separate deb packages for python3-pyudev and python-pyudev, so the pull request updates deb package dependency as well.
Under Arch, python-pyudev contains code for python3 so no update is required. Probably the same for Gentoo, but could not check that.
=> scripts/debian: switch to python3

lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/status.py
The Logitech specs say that 0 for BatteryDischargeLevel in 0x1000 is not 0% but is instead unknown.  Solaar incorrectly records it as 0%.   Fortunately most uses of this information handle None specially, so not much code needs to be changed.
Fixes #265 
I don't have the hardware to test this but have asked the reporters to test it.
=> receiver: battery level 0 is unknown level

docs/capabilities.md, lib/logitech_receiver/base_usb.py, lib/logitech_receiver/receiver.py, lib/solaar/cli/pair.py, lib/solaar/cli/show.py, lib/solaar/cli/unpair.py, lib/solaar/listener.py, lib/solaar/ui/pair_window.py, lib/solaar/ui/window.py
Correctly handle receivers like the c534:
Support devices that only allow a limited number of total re-pairings
Support devices that do not unpair or when pairing replace existing pairings
Add information about max_pairings, unpairing, and re-pairing to the list of receivers by USB id
Set up c534 as receiver with max 2 pairings, no unpairing, re-pairing
It may be that all nano receivers work the same way as the c534.  This PR only sets up the c534, as that is the only nano receiver I have access to.  Changing all nano receivers to work this way is simply a matter of changing _nano_receiver in base_usb.py
This updates PR #614
=> Support receivers that don't unpair but replace when pairing, like c534

lib/logitech_receiver/base_usb.py, lib/logitech_receiver/receiver.py, lib/solaar/cli/unpair.py, lib/solaar/ui/window.py
Make other nano receivers not unpair and replace when pairing.   Extends PR #674
I don't have any such receivers so I am unable to test whether all nano receivers work this way.
Fixes #406
=> Extend changes for c534 to all nano receivers

lib/solaar/ui/notify.py
Window manager notifications were turned off with PR #382 commit ea80c6d6
I'm running Fedora 31 and this is no longer a problem so maybe notifications should be turned on again.
However, #335 is about disabling notifications so maybe notifications should remain off.
I rather like the notifications, so I'm putting in this PR so that the issue can be considered.
=> ui: turn on window manager notifications again

lib/solaar/ui/pair_window.py
I messed up the logic for showing the warning in the pairing window. 
Now the warning only shows up for devices that have a limited number of pairings.
=> ui: don't show warning in pairing window for receivers with unlimited pairing

lib/solaar/ui/window.py
Using some code in a suggestion in #662 I added a quit button to the main window.
This allows completely quitting Solaar from the main window when the tray is active instead of having to quit from the tray.
Replacement for PR #663 
Note comment against this change by @mickleby
=> ui: add quit button to main window

lib/logitech_receiver/base.py, lib/logitech_receiver/notifications.py
Solaar creates notifications for DJ reports, e.g., mouse movement and keystrokes.  
Solaar treats DJ notifications as HID++ 1.0 notifications resulting in warnings and errors.
This PR does not create notifications for DJ mouse movement and keystroke reports.
This PR segregates DJ notifications into their own handler, which currently ignores them all as the events that might cause changes have HID++ 1.0 notifications as well.
Instead of halting Solaar when a message with unexpected report id or size is found, log a waning and ignore the message.   This was tested by removing information on one of the expected report ids and size - Solaar correctly handled the now-unexpected messages.
=> better handling of DJ notifications and reports; don't halt on unexpected report IDs or lengths

docs/index.md
To fix a dummy URL inadvertently left in the documentation.
=> docs: replace dummy URL for Solaar with real URL

packaging/build_deb.sh, packaging/debian/rules
I was communicating with the contact person for the ubuntu packages about updating, and mentioned that python3 is required now.  The contact person pointed to some remaining bits where python2 is used, so I'm changing them to python3.
=> packaging: remove last vestiges of python2

lib/logitech_receiver/settings_templates.py
safely handle errors with check_feature to allow devices to be detected even if some features are inconsistent
Separated from https://github.com/pwr-Solaar/Solaar/pull/684
Test results are identical
=> Add safety for non-compliant mouse features

docs/debian.md, docs/index.md, packaging/debian/control
After much discussion, it seems `solaar-gnome3` is no longer needed, as the `solaar` package handles app indicators perfectly, and there appears to be no more use case for `solaar-gnome3` as a separate package. 
Addresses https://github.com/pwr-Solaar/Solaar/issues/656
=> Remove solaar-gnome3

.github/ISSUE_TEMPLATE/bug_report.md
Diagnosing bugs would be easier if the bug report included the commit for bugs in versions of Solaar from the repository.
=> docs: ask for git describe output if running a cloned version

lib/logitech_receiver/status.py, lib/solaar/upower.py
Upower no longer emits signals for suspend/resume.  I update to the current logind signals.
I left the old signals just in case some distribution uses them.
Also fix a bug for devices that haven't been completely initialized.
Fixes #692 
Should solve #686 and maybe some older bugs
=> add logind signal for suspend/resume

lib/logitech_receiver/settings_templates.py, lib/solaar/gtk.py, lib/solaar/listener.py, lib/solaar/upower.py
There was nothing that told Solaar that device settings needed to be re-applied after a resume, which needs to be done because the device might have been turned off and on again, or gone into some other mode that loses settings, while the computer was suspended.
Also don't check features when the device is offline.
Also fix style in adding logind suspend/resume dbus watcher.
Addresses #686
=> Fix bug in not applying settings after resume

lib/logitech_receiver/base_usb.py, rules.d/42-logitech-unify-permissions.rules
replaces https://github.com/pwr-Solaar/Solaar/pull/659
This is the last bit to add support for the c537 nano receiver. Credit goes to @pfps for the changes. 
Combined with a number of other branches that have been merged it now also has preliminary support for the G602, partially addressing https://github.com/pwr-Solaar/Solaar/issues/128
Test results look good and clean:
```
sudo python3 ./bin/solaar -dd 
[sudo] password for rijnhard:          
10:44:37,214     INFO [MainThread] root: language en_ZA (UTF-8), translations path /Data/OpenSource/Solaar/share/locale
10:44:37,374    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
10:44:37,437     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
10:44:37,486    DEBUG [MainThread] solaar.ui: …
```
=> Add Support for C537

docs/installation.md, lib/solaar/gtk.py
Change installation.md to use python3 names for required system packages.
Change gtk.py to output python3 names for missing system packages.
=> docs: improve documentation on required system packages

lib/solaar/ui/tray.py
Fixes #698 
I'm a bit leery about adding this to Solaar because it might introduce new bugs.
The bug causing #698 is not in Solaar.  The situation is not very likely to arise.  
On the other hand, when the bug does arise finding out what went wrong is very hard.
=> UI: lookup icon filenames directly to get around bug in libappindicator

lib/logitech_receiver/receiver.py, lib/solaar/cli/unpair.py
The command line interface generally just does the command without checking whether it makes sense to Solaar, on the assumption that users of the CLI know what they are doing.  When I fixed up the unpairing for Nano receivers I had to handle unpairing differently for Universal and Nano receivers so the low-level code didn't try to unpair for Nano receivers. This PR adds in a forced unpair and uses that version in ``solaar unpair <n>``, restoring the old behaviour for the CLI.
=> cli: force unpairing attempt when using cli

lib/solaar/ui/tray.py
The original PR didn't fix up the problem when setting the attention icon.
=> also look up attention icon filename to get around libappindicator bug

lib/logitech_receiver/receiver.py
This fixes an error introduced in PR #702
=> receiver: remove extra argument in call when unpairing

lib/solaar/ui/tray.py
This PR will fix some issues with the tray icon:
- missing parentheses to a function call,
- missing reinitialization of `_icon_before_attention` after iteration of `_blink()`,
- slightly tweaking the tooltip description (always showing the program's name just once).
=> ui: a few tray icon fixes

docs/installation.md, lib/solaar/gtk.py
The code had a require_version for Gtk 3.0 before the call to the _require function that caught the exception.  This change moves that check into the _require function so that the error message is printed instead of dumping core.
Fixes #462 
I checked the code by setting up a Fedora container and running solaar from within the container with several variations of packages installed.
=> install: fix up errors when required packages not installed

ChangeLog, docs/installation.md, lib/solaar/ui/tray.py, packaging/debian/control, setup.py
Unity's libappindicator is deprecated in Debian since almost more than two years (for several reasons). This also includes Debian 10 (buster) which is the current stable distribution. For more information, please have a look at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037 and https://wiki.debian.org/Ayatana/IndicatorsTransition.
They started to use [GNOME's libayatana-appindicator](https://ayatanaindicators.github.io/) instead which is a maintained fork of Unity's libappindicator. libayatana-appindicator has also been in Ubuntu since Ubuntu 18.04LTS (bionic beaver). So users of Ubuntu Budgie, Kubuntu and Xubuntu can also benefit from this additional support.
Please consider this PR to support the transition to Ayatana Indicators.
=> ui: support Ayatana AppIndicator

lib/solaar/ui/icons.py
Makes battery level of low map into low icons instead of critical icons for several themes.
Fixes #723
=> ui: more flexible way to determine icon from battery level

docs/index.md
Add suggestion not to use old version from repositories.
Remove second pointer to Ubuntu PPAs.
=> docs: update information on pre-built packages

lib/logitech_receiver/settings.py
Combined devices like the K400 have a keyboard and a trackpad but identify as keyboards so they can break the assumption that the kind of a feature matches the kind of the device.  To fix this remove the check in settings.py for this match.  Otherwise there would have to be special information about these kinds of devices and the check isn't doing anything particularly useful.
The feature in question for the K400 is hi res scroll.
Fixes #266
=> receiver: don't check that device kind matches feature kind

lib/solaar/ui/tray.py
Explicit paths don't seem to scale the same as icon names so only use one if absolutely necessary to get around GTK bug causing #698
Fixes #698
=> ui: only use explicit file path for tray icon if icon name is file in current directory

setup.py
The long description shows up in several places and was rather short.  I added that Solaar can change device features.
=> docs: add changing device features to long description of Solaar

docs/devices.md
I have this mouse and I was confused at the beginning if this would be a different model but then I saw the same WPID so I thought of just fixing the typo.
=> docs: dixed name typo for MX Master 2S

lib/solaar/ui/notify.py, share/applications/solaar.desktop
GNOME requires that notifications have a 'desktop-entry' hint to be
able to filter notifications by application. See
https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource.
Fixes pwr-Solaar/Solaar#734
=> ui: add 'desktop-entry' hint to indicate notification source.

lib/solaar/ui/window.py
The assert was violated in a few cases where nothing seemed to be wrong.
I looked over the code and it doesn't appear that anything bad will happen if the condition is false.
Fixes #651
=> ui: remove assert that updated receiver is still in window

docs/capabilities.md, lib/solaar/ui/icons.py, lib/solaar/ui/tray.py
The scheme to use the best ones is too complex and error-prone.
Symbolic icons are problematic because of external bug with dark themes and icons in the system tray.
As a temporary hack, add an environment variable to use symbolic icons in tray.
Fixes #456 #746
=> Use only standard battery icons

ChangeLog, docs/_config.yml, lib/solaar/__init__.py, release.sh, setup.py
Note that this PR removes the hyphen before rc2, as this seems to be what Python releases want.
=> prepare for release 1.0.2rc2

ChangeLog, lib/solaar/ui/icons.py
It's silly to check and warn about a missing icon but then try to use it.
=> ui: use Solaar icon instead of missing battery icons

RELEASE.md
It did not mention all the places where the release number needs to be changed.
It did not mention that the release commit needs to be pushed to the Solaar repository.
It had the old way to name release candidates.
=> release: fix up RELEASE.md

.gitignore
setup.py creates lib/solaar.egg-info/ so add it to .gitignore
=> git: add lib/solaar.egg-info/ to .gitignore

docs/capabilities.md, lib/solaar/gtk.py, lib/solaar/ui/icons.py, lib/solaar/ui/tray.py
This is a better solution than using an environment variable, although it probably means supporting the option for the forseeable future.
Fixes #768
Fixes #84
=> ui: add --battery-icons=symbolic option to prefer symbolic icons

lib/logitech_receiver/settings_templates.py
Fixes problem with displaying dpi in main window.
It would be good to also have a "tooltip" for _DPI and _POINTER_SPEED but I don't know what should be put there.
See #776 for an example of the suboptimal output.
=> devices: pass arguments through in feature_choices_dynamic

ChangeLog, lib/solaar/listener.py
If a receiver is not writable but has an ACL it is for another seat so don't complain.
Using the python interface to ACL is nicer but has dependencies, which is not good for such an edge case.
Fixes #391
=> ui: don't complain for receivers in other seats

lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/solaar/cli/show.py
`solaar show` uses Settings interface to show values for features if there is no built-in code to show feature.
Also comment out code for feature LOWRES_WHEEL as the Settings interface does a good job on this feature.
This means that new HID++ features do not need to be implemented in show.py or in hidpp20.py, only in settings_templates.py.
Fixes #687
=> use Settings interface in `solaar show`

lib/logitech_receiver/receiver.py, lib/logitech_receiver/settings_templates.py
This used to be checked when switching the shown device in the  main window, leading to slow response, as the UI had to wait for all the device features to be checked.  This change only checks for the device features when nothing is known about the device, on the plausible assumption that the features that a device implements doesn't change.
=> only check device features once per device, not every time device settings are enumerated

lib/logitech_receiver/base.py
Documentation on DJ shows which 0x20 reports are not notifications.
Addresses part of #815
=> receiver: filter out DJ reports that are not notifications

lib/logitech_receiver/receiver.py
The implementation of `feature_map_choices_dynamic` returns `None` when no choices are available. 
https://github.com/pwr-Solaar/Solaar/blob/c5ca2c2818fdd81647b2959a9433edf333e4af2b/lib/logitech_receiver/settings_templates.py#L158-L160
In that case, `None` should not be stored among real settings, otherwise several errors occur when the setting is listed on [descriptors.py](https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/descriptors.py). Example of error:
```
File "…/Solaar/lib/solaar/ui/window.py", line 381, in _device_selected
_update_info_panel(device, full=True)
File "…/Solaar/lib/solaar/ui/window.py", line 721, in _update_info_panel
_update_device_panel(device, _info._device, _info._buttons, full)
File "…/Solaar/lib/solaar/ui/window.py", line 692, in …
```
=> receiver: fix error when settings listed on descriptor.py return None

docs/features.md, lib/logitech_receiver/hidpp20.py, lib/solaar/cli/show.py
=> receiver: gather host names from HOSTS_INFO feature and show them

lib/logitech_receiver/settings_templates.py, lib/solaar/cli/config.py
Internal number are from 0 to n-1, but the ones used in Logitech software that are visible to users are from 1 to n.
=> receiver: adjust CHANGE_HOST numbers to user-visible ones

docs/devices.md, docs/devices/ex100.txt, lib/logitech_receiver/base_usb.py, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/hidpp10.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py, lib/solaar/cli/show.py
docs: add EX100 keyboard/mouse combo
receiver: add EX100 27 MHz receiver (046d:c517), removed incorrectly 
listed as nano receiver, add workarounds for EX100 wpids
device: add EX100 keyboard and mouse
hidpp10: fix notification parsing, add device features flags
notifications: fix wpid processing for 27 MHz protocol
cli: add display of device features flags for HID++ 1.0 devices
Fixes #347
=> Add EX100 keyboard/mouse combo and support for 27 MHz receiver

lib/logitech_receiver/receiver.py
The implementation of dynamic features causes some exceptions when we click the name of an **idle** device. An example:
<details>
```
File "…/Solaar/lib/solaar/ui/window.py", line 395, in _device_selected
_update_info_panel(device, full=True)
File "…/Solaar/lib/solaar/ui/window.py", line 759, in _update_info_panel
_update_device_panel(device, _info._device, _info._buttons, full)
File "…/Solaar/lib/solaar/ui/window.py", line 730, in _update_device_panel
_config_panel.update(device, is_online)
File "…/Solaar/lib/solaar/ui/config_panel.py", line 292, in update
for s in device.settings:
File "…/Solaar/lib/logitech_receiver/receiver.py", line 275, in settings
self._settings = [s(self) for s in self.descriptor.settings]
File …
```
=> Idle devices - exceptions caused by dynamic features

docs/README.md, docs/capabilities.md, docs/debian.md, docs/devices.md, docs/features.md, docs/i18n.md, docs/index.md, docs/installation.md, docs/usage.md
Mostly just linting and spellchecking, but also rephrased a few places. Some URLs are made relative, to facilitate testing at other sites (ie. https://jeblad.github.io/Solaar/).
The cleanup is done in VScode, with LanguageTool, Spell Right, and markdownlint. I have not added the dict-files, if necessary that can be done.
=> Cleanup and lint the docs

docs/index.md
Needed because the project README.md links to this file.
See PR #900
=> docs: put absolute links back in index.md

lib/logitech_receiver/notifications.py, lib/logitech_receiver/status.py
=> receiver: don't produce pop-up notifications at startup and power on

lib/logitech_receiver/settings_templates.py
=> receiver: correctly handle settings that share a name in config

docs/devices.md, docs/features.md, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/solaar/cli/show.py, lib/solaar/ui/config_panel.py, lib/solaar/ui/window.py
Closes #411.
Closes #788.
This is a follow-up to #934 and #788.
I didn't use the set and get methods directly from Gesture because I tried to avoid unnecessary requests, which is possible because we can read and write options that share an offset in a single request. 
@pfps, thank you for writing the code of #934 (upon which this PR is based). I retained your old commit, as I didn't know a good way to replace it with your updates after I made a lot of changes.
So far, I've only implemented the boolean settings. I tried to make the UI look better than that ugly hack I had written (#818), but it still has some alignment issues. The UI changes also apply to KEYBOARD_DISABLE_KEYS. 
Of course, corrections and ideas are welcome.
=> Support for GESTURE_2 settings

lib/solaar/ui/about.py
Just a small fix!
The link in the about was not working and I just put the link provided in the github page.
=> Fix broken link to about website

docs/devices.md, lib/hidapi/__init__.py, lib/hidapi/udev.py, lib/logitech_receiver/base_usb.py, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/device.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py
udev: add function to get wpid from device path
base: make workaround flag name more generic
descriptors: fix wpid's for 27Mhz devices
device: Improve wpid and kind processing for 27Mhz devices
notifications: Improve wpid generation for 27Mhz devices
docs: fix wpid's for EX100
=> Improve 27 MHz devices handling

lib/hidapi/udev.py, lib/logitech_receiver/base.py, lib/logitech_receiver/base_usb.py, lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/receiver.py, lib/solaar/cli/__init__.py, lib/solaar/cli/probe.py, lib/solaar/cli/show.py, lib/solaar/configuration.py, lib/solaar/listener.py, lib/solaar/ui/config_panel.py, lib/solaar/ui/tray.py, lib/solaar/ui/window.py, rules.d/42-logitech-unify-permissions.rules
Adds wired devices that talk HID++ 2.0 to the Solaar GUI.
Also adds G502 Hero mouse USB information
Also lets config and probe work on wired devices
Also adds more information to show
Replaces #952
=> Add wired devices to Solaar GUI

lib/logitech_receiver/descriptors.py, lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py, lib/logitech_receiver/settings_templates.py, lib/logitech_receiver/status.py, lib/solaar/listener.py, lib/solaar/ui/__init__.py, lib/solaar/ui/notify.py, lib/solaar/ui/window.py
Closes #573
Implementation status:
=> devices: support for MX Vertical mouse

lib/logitech_receiver/descriptors.py
Hello!
Here is the device information for the MX Keys keyboard.
It works flawlessly with it. :-)
Thanks a lot for your awesome work!
Cheers,
Olivier
=> device: add BT information for MX Keys

docs/devices.md, lib/hidapi/udev.py, lib/logitech_receiver/base.py, lib/logitech_receiver/base_usb.py
Support USB-connected and Bluetooth devices that do not have any entry in descriptors.py by matching udev devices that have Logitech for vendor and a product ID in the ranges that Logitech uses for these devices.
=> device: support unknown USB-connected and Bluetooth devices

lib/solaar/ui/__init__.py
* Fixes the following warning I was getting after every single call to `solaar`:
```
/usr/lib/python3.8/site-packages/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
```
=> Fix PyGIWarning

lib/logitech_receiver/diversion.py, lib/solaar/ui/diversion_rules.py, lib/solaar/ui/window.py
See discussion in #988.
This PR adds a GUI to display, create and edit diversion rules. It still needs to be improved in many ways, but it's already functional. It displays built-in rules (read-only) and rules defined by the user (which are editable). To see the available options, right-click a row. To edit the contents of a row, click it and change the values on the bottom panel. For types that require a string from a list, suggestions are shown under the text field in a case-insensitive way, ignoring underscores and spaces, considering any allowed value that contains the input text as a substring at any position (e.g. for `KeyPress`, typing "volume" shows the suggestions `XF86_AudioLowerVolume` and `XF86_AudioRaiseVolume`).
TESTING SUGGESTIONS:  
Before testing, read docs/rules.md so …
=> GUI for changing Notification Rules

lib/logitech_receiver/settings.py, lib/solaar/configuration.py
Reduce the frequency of changing the configuration file unnecessarily by comparing the old value of a setting with the new value, when possible, and only saving if the value actually changed.
=> receiver: reduce unnecessary writes of config file

docs/capabilities.md, docs/rules.md, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/diversion.py, lib/solaar/ui/diversion_rules.py
Fixes #1006 
Much of rule processing requires X11 so turn off rule processing if X11 is not available.
=> rules: make rule processing conditional on X11 being available

lib/logitech_receiver/diversion.py
The current version prints an obscure warning when it can't connect to xorg. As the result, troubleshooting requires modifying code even when maximum log verbosity is enabled (`-dd`).
This change adds the real exception to the logs.
=> Log real exception when can't use Xorg API

lib/solaar/cli/__init__.py, lib/solaar/cli/config.py, lib/solaar/cli/show.py, lib/solaar/cli/unpair.py
Fixes an issue when trying to configure a device that is connected via BT or USB but is also paired with a connected receiver.
=> cli: don't select paired but not connected device for config command

lib/logitech_receiver/device.py, lib/logitech_receiver/settings_templates.py
Some devices signal errors if the message is short for a feature that expects more bytes.
=> device: use long messages for all 2.0 requests

lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/settings_templates.py, lib/solaar/cli/show.py
Fixes #1040
As described in https://github.com/pwr-Solaar/Solaar/issues/1040,
this implements the ability to change report rates for HID++ 2.0+
devices by first sending the device into Host-mode before
modification.
=> setting: implement polling rate

docs/index.md, lib/solaar/ui/action.py, lib/solaar/ui/diversion_rules.py, lib/solaar/ui/icons.py, lib/solaar/ui/tray.py
Only add one path to theme paths because all the extra icons are in one directory.
Don't use a :-joined list of paths in appindicator.
Can be tested by anyone.  Check that icons show up correctly both in the main window and in the tray, particularly the solaar icons.
=> better handling of icon search paths and better icon handling

docs/capabilities.md, docs/index.md, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/logitech_receiver/status.py, lib/solaar/cli/config.py, lib/solaar/ui/config_panel.py
This ability was added to permit Solaar to coexist with both old drivers - where users may need to set scroll wheel resolution to achieve good scrolling speed - and new drivers - where Solaar should not change the value for scroll wheel resolution.
Fixes  #1061 and #1112 and #1132.
=> ui: add ability to ignore a Solaar setting

docs/index.md, lib/logitech_receiver/settings_templates.py
Fixes #1139 
To prevent Solaar from writing the report rate, mark the Polling Rate as ignored by clicking on the icon at the right side of the setting until the red icon appears.  By that time Solaar will have already set profiles to host mode so the device will need to be turned off and on again.
=> only set profile host mode when actually writing report rate

docs/capabilities.md, docs/rules.md, lib/logitech_receiver/diversion.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py
Addresses #1108 
Adds a Mouse Gestures setting.  When turned on, and the mouse's App Switch Gesture button is diverted, pressing and then releasing the App Switch Gesture button causes mouse x and y displacement while the button is down to be converted into a fake notification that can be used in Solaar rules.   The easiest way to build rules for these gestures is via mouse-left, mouse-right, mouse-down, and mouse-up tests.
=> settings: add mouse gesture handling

docs/rules.md, lib/logitech_receiver/diversion.py, lib/logitech_receiver/settings.py, lib/solaar/ui/diversion_rules.py
- Remove existing mouse-* Test types
- Add new 'Mouse Gesture' Condition
- Implement Rule Editor UI for it
- Add support for diverted buttons in gestures
- Added diagonal mouse gesture directions (up-left, down-right, etc)
Allows you to chain multiple movements/buttons (for instance, moving the mouse up and then left) together into a single mappable gesture.
=> Add more robust mouse gesture support

docs/rules.md, lib/logitech_receiver/diversion.py, lib/logitech_receiver/special_keys.py, lib/solaar/ui/diversion_rules.py
- Track `key_up` key in addition to `key_down`
- Support `pressed` or `released` action in `Key` condition
- Add radio button to KeyUI to represent `pressed` or `released`
Push to talk with a mouse button: Bind `pressed` and `released` events to microphone unmute and mute commands respectively
Implements #1186
=> diversion: implement pressed and released action on Key condition

lib/logitech_receiver/diversion.py
When I was trying to define rules for the G keys of a G613, I got the error message "'int' object is not subscriptable". With this fix it works.
=> Fix issue with G keys

docs/installation.md, lib/logitech_receiver/status.py
Fixes bug with devices that don't provide battery information when they cause resume from suspend.
Fixes #1249
=> device: don't signal status change when battery changes from None to None

lib/solaar/ui/tray.py
Gets around a bug in XFCE system tray implementation.
=> ui: use file names for tray icon to not end up with small icons

lib/logitech_receiver/diversion.py
Fix for process windows identified as having WM_CLASS 'FocusProxy' like Java programs. #1322
=> Fix for process windows identified as having WM_CLASS 'FocusProxy'

docs/devices.md, lib/logitech_receiver/base_usb.py
Fixes #1350
Receiver 0xC542 does not appear to use the HID++ protocol so Solaar does not work with it.
=> receiver: sort receiver list and document receiver 0xC542

docs/devices.md
Without any space between the heading and the table, the rendering on GitHub Pages breaks (see screenshot below).
=> docs: fix table rendering on GitHub Pages

ChangeLog, docs/installation.md
While reading the changelog for the latest release, I found a typo. I ended up running a spellcheck on the changelog and `docs` directory, and found a bunch of other mistakes too.
=> Changelog: fix typos

lib/logitech_receiver/base_usb.py, share/solaar/io.github.pwr_solaar.solaar.metainfo.xml
This allows AppStream-based tools to suggest installing Solaar when a
supported device is detected. The list of ids is based on
lib/logitech_receiver/base_usb.py.
While we're at it, sort the ids in lib/logitech_receiver/base_usb.py
and add a comment there to request updates to metainfo. Also add the
solaar binary to metainfo.
Signed-off-by: Stephen Kitt <steve@sk2.org>
=> Add modalias globs for supported hardware

lib/solaar/ui/window.py
When resizing the window or switching entries in the left tree, the width of the tree changes and takes more space then needed.
Switch it over to only take the minimal amount of space and do not extend when resizing the window.
=> Keep left Tree at Minimal Size

lib/solaar/ui/config_panel.py
Instead of GtkEventBox use GtkButton for the lock icons.
GtkEventBox does not have any visual feedback that it actually can be pressed. As in: If you don't know that this is an area for interaction it is not obvious.
Using Gtk.ReliefStyle.NONE on the GtkButton keeps the old styling but still gives feedback when hovering over the buttons.
=> Use GtkButton for the Lock Icon

lib/solaar/ui/icons.py
=> use monochrome icon when using symbolic icons

setup.py
RHEL8 and derivatives carry PyYAML 3.12 and psutil 5.4.3 built for the default python 3.6 in the base OS repository. Consequently, solaar is not installable without installing python38 or python39 stack (called module in RHEL/Fedora) that carry newer versions of these two.
solaar seems to work fine with these older versions as [confirmed](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-f65a1a9d86) by @mefuller .
Fixes #1418 .
=> lower PyYAML and psutil version requirements

docs/index.md, lib/logitech_receiver/settings_templates.py
Fixes #1494 
Polling Rate no longer disables onboard profiles.
=> settings: add setting to disable Onboard Profiles

docs/index.md, docs/installation.md, docs/rules.md, lib/logitech_receiver/diversion.py
Fixes #1020 
Requires write access to /dev/uinput.  Use `sudo setfacl -m u:${user}:rw /dev/uinput`.
=> rules: use uinput to simulate keyboard input if XTest does not work

setup.py
1.1.2 is still commonplace, e.g. in older Fedora, RHEL/CentOS 8 and Debian 10. Current code doesn't use any new features from 1.3.0.
=> lower python-evdev requirement to 1.1.2

lib/solaar/cli/config.py, lib/solaar/ui/__init__.py
The application advertises itself as io.github.pwr_solaar.solaar through
its appdata file, so name the application this way too.
This fixes this warning in Flatpak:
```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```
I went with `io.github.pwr_solaar.solaar` as `io.github.pwr.solaar` doesn't seem like a correct reverse DNS name.
=> Make APP_ID match real application ID

docs/rules.md
=> doc: add information on how to find divertable key names in solaar show output

share/solaar/io.github.pwr_solaar.solaar.metainfo.xml
Fix release date for 1.1.4: month should be "07" instead of "77".
=> Fix release date in io.github.pwr_solaar.solaar.metainfo.xml

lib/logitech_receiver/diversion.py
Fix this circular import error found while attempting to package Solaar in Fedora
```
Check import: logitech_receiver.diversion
/builddir/build/BUILDROOT/python-solaar-1.1.4-1.fc37.x86_64/usr/lib/python3.11/site-packages/logitech_receiver/diversion.py:35: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
from gi.repository import Gdk, GLib
File "/usr/lib/rpm/redhat/import_all_modules.py", line 171, in <module>
main()
File "/usr/lib/rpm/redhat/import_all_modules.py", line 167, in main
import_modules(modules)
File "/usr/lib/rpm/redhat/import_all_modules.py", line 100, in import_modules
importlib.import_module(module)
File …
```
=> Fix circular import

lib/logitech_receiver/settings_templates.py
Fixes #1662 but is only a hack.  Waiting on information on updated feature to fix correctly.
=> settings: ignore first mouse gestures movement event for feature version 5 (solves MX Master 3S problem)

lib/solaar/cli/config.py
solaar config leaves the device alone except for any change in the command line
=> cli: don't apply settings in solaar config

docs/devices/Wireless Keyboard K470 4075.txt, lib/logitech_receiver/descriptors.py
The K470 is the keyboard included in the MK470 Slim Wireless Keyboard and Mouse Combo: https://www.logitech.com/en-us/products/combos/mk470-slim-wireless-keyboard-mouse.html
The mouse in this combo is M340, with almost identical appearance of the Logitech Pebble M350 mouse, but has the same WPID of the M185 new (4054).
=> Add PID of the K470 keyboard from the MK470 combo

docs/devices/G535 Wireless Gaming Headset 0AC4.txt, docs/devices/Number Pad N545 2006.txt, lib/logitech_receiver/device.py
=> device: correctly determine whether to ping with a long HID++ message

lib/solaar/ui/window.py
when running solaar with verbose logging I found the message was being emitted:
```
(solaar:64699): Gtk-WARNING **: 17:18:05.225: Failed to set text '<small><tt>Path         : /dev/hidraw5
Index        : 255
Product ID   : 046d:C092
Protocol     : HID++ 4.2
Polling rate : 1 ms (1000Hz)
Serial       : 
Unit ID      : 1D002800
Bootloader : BL1 17.00.B0005
Firmware   : U1  52.00.B0010
Firmware   : ' from markup due to error parsing markup: Error on line 10 char 25: Element “markup” was closed, but the currently open element is “tt”
```
After investigation, I found this was because my G203 mouse was returning the following firmware values:
```
>>> device.firmware
(FirmwareInfo(kind=NamedInt(1, 'Bootloader'), name='BL1', version='17.00.B0005', extras=b'\xaa\xfd'),
FirmwareInfo(kind=NamedInt(0, …
```
=> Filter and escape technical detail fields

docs/rules.md
Fixed a few cases of backquote mistakes, unescaped <>, and misc language typos.
Took the liberty to unitalicise the third paragraph. Obviously it's important, but an entire paragraph in italics is hard to read.
I noticed there were two slightly different paragraphs about Setting conditions, which I assume is a mistake. I don't know which is better than the other, so I simply moved them next to each other for ease of comparison and manual merging/editing.
=> Fix punctuation and language in rules.md

docs/devices.md
When I read https://pwr-solaar.github.io/Solaar/devices to see whether MX Vertical is supported before I buy it, it confused me for a bit, until I find it being supported in the forums. This change adds the mouse to the list (verified it actually works by running `solaar show` in version 1.1.1).
=> add MX Vertical mouse to the list of devices

docs/installation.md, lib/logitech_receiver/diversion.py, setup.py
This utilises https://github.com/sidevesh/solaar-gnome-extension gnome extension to get wm_class of focus and pointer focus window under wayland in gnome-shell.
Also, let me know if @pfps you would want to include the source of the gnome extension in this repo or org.
Closes #1747
=> Add support for process condition under wayland using solaar-gnome-extension

rules.d-uinput/42-logitech-unify-permissions.rules, rules.d/42-logitech-unify-permissions.rules
This was only needed for Ubuntu releases that are all now EOL.
=> Remove udev-acl tag from udev rules

docs/index.md
[`community` was merged into `extra`](https://archlinux.org/news/git-migration-announcement/).
=> Update Arch repository name and link

setup.py
these only have meaning when they end up in a directory scanned by udev, so $prefix/lib/udev/rules.d will be correct when installed to /usr. this changes it from /usr/share/solaar/udev-rules.d which is ignored. it does not affect installing as a user (e.g. pip install --user)  
closes #2142
=> dist: install .rules to correct place by default

lib/logitech_receiver/common.py
The equality test of `NamedInt` returns None when it is compared to a None, it should return False instead. This is problematic because the equality test of `Device` (`lib/logitech_receiver/device.py`) depends on it.
```python
def __eq__(self, other):
return other is not None and self._kind == other._kind and self.wpid == other.wpid
```
So that if one of the devices' `_kind` is None, this equality test would return None.
And that, in turn, makes the Device condition (`lib/logitech_receiver/diversion.py`) return None, which stops the processing of the remaining rules.
That means, if a connected device has a `_kind` of None and it sends a HID++ notification, then a failure of a Device condition in an earlier rule would prevent later rules from being processed.
This commit fixes that.
=> NamedInt: return False on comparison with None

docs/rules.md, lib/logitech_receiver/diversion.py
=> rules: fix test for device equality

lib/logitech_receiver/descriptors.py
Fixes #2196 
Test:
"solaar show" no longer breaks.
=> device: add K845 keyboard

release.sh
Fix changelog parsing in release.sh after conversion to markdown d57af51.
It used to be `Version :` but then it was changed to `# Version`, thus parsing was broken.
So now it actually uses info from `ChangeLog.md`, compare
https://github.com/antonsoroko/Solaar/releases/tag/1.1.10
with
https://github.com/antonsoroko/Solaar/releases/tag/1.1.11
=> Fix changelog parsing in release.sh after conversion to markdown

release.sh
To be used in PPA builds.
for https://github.com/pwr-Solaar/Solaar/issues/2186#issuecomment-1917541259
this will allow to make PPA build without manual changing of tag name in PPA recipe every time there is a release, instead we will use "stable" branch as branch name.
Tested by creating new releases:
from https://github.com/antonsoroko/Solaar/tree/version_1.1.11 i created
https://github.com/antonsoroko/Solaar/tree/1.1.11
and https://github.com/antonsoroko/Solaar/tree/stable used to point to that `1.1.11` tag.
then from https://github.com/antonsoroko/Solaar/tree/version_1.1.12 i created
https://github.com/antonsoroko/Solaar/tree/1.1.12
and https://github.com/antonsoroko/Solaar/tree/stable points to that new `1.1.12` tag.
see https://github.com/antonsoroko/Solaar/commits/stable/
=> Add stable branch to release.sh

docs/i18n.md
```
$ ./tools/po-update.sh ru
/usr/bin/msgunfmt: error while opening "/usr/share/locale-langpack/ru/LC_MESSAGES/gtk30.mo" for reading: No such file or directory
/usr/bin/msgunfmt: error while opening "/usr/share/locale-langpack/ru/LC_MESSAGES/gtk30-properties.mo" for reading: No such file ordirectory
/usr/bin/msgmerge: error while opening "" for reading: No such file or directory
```
```
$ ./tools/po-update.sh en
Created /home/antix/work/Solaar/po/en.po.
/usr/bin/msgunfmt: error while opening "/usr/share/locale-langpack/en/LC_MESSAGES/gtk30.mo" for reading: No such file or directory
/usr/bin/msgunfmt: error while opening "/usr/share/locale-langpack/en/LC_MESSAGES/gtk30-properties.mo" for reading: No such file ordirectory
/usr/bin/msgmerge: error while opening "" for reading: No such file …
```
=> Mention language pack for Gnome in i18n.md

lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/solaar/ui/config_panel.py
=> device: support backlight on MX Keys S

docs/capabilities.md, lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/solaar/ui/config_panel.py, setup.py
This PR adds settings for feature x8070 COLOR LED EFFECTS.   
To set a color effect, edit `~/.config/solaar/config.yaml`, after first running this version of Solaar to have the possible color zones determined.  There will a line in the file with key `led_zone_n` for each color zone.  Unfortunately some mice do not report the current effect for the zones so the value is likely to be simple.  The information on effects is stored in a slightly different way than for profiles on devices - Solaar uses LEDEffectSetting in profiles and LEDEffectIndexed in config.yaml.
=> support color feature for many devices

lib/solaar/ui/config_panel.py, lib/solaar/ui/window.py
=> ui: tidy up scrolling appearance in configuration panel

.github/workflows/tests.yml, setup.py
=> Setup automated macOS tests using GitHub action

share/solaar/io.github.pwr_solaar.solaar.metainfo.xml
Flathub requires this tag: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name.
The format of this tag is defined in https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer.
=> Add the <developer/> tag in the metainfo

lib/hidapi/hidapi.py, lib/hidapi/hidconsole.py, lib/hidapi/udev.py, lib/logitech_receiver/__init__.py, lib/logitech_receiver/base.py, lib/logitech_receiver/base_usb.py, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/device.py, lib/logitech_receiver/diversion.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py, lib/logitech_receiver/settings_templates.py, lib/solaar/cli/__init__.py, lib/solaar/configuration.py, lib/solaar/gtk.py, lib/solaar/i18n.py, lib/solaar/listener.py, lib/solaar/ui/__init__.py, lib/solaar/ui/about.py, lib/solaar/ui/action.py, lib/solaar/ui/common.py, lib/solaar/ui/config_panel.py, lib/solaar/ui/notify.py, lib/solaar/ui/tray.py, lib/solaar/ui/window.py, setup.py
=> break up imports loops except for calls to GUI functions from logitech_receiver code

.github/workflows/checks.yml, .github/workflows/tests.yml, Makefile, setup.py
Upgrade actions leveraging Node.js 20
#2256, #2284
=> Fix deprecated GitHub actions

lib/logitech_receiver/device.py, lib/logitech_receiver/diversion.py, lib/logitech_receiver/notifications.py, lib/logitech_receiver/receiver.py, lib/logitech_receiver/settings.py, lib/logitech_receiver/settings_templates.py, lib/logitech_receiver/status.py, lib/solaar/gtk.py, lib/solaar/listener.py, lib/solaar/ui/__init__.py
=> add a callback to signal changes to settings

lib/logitech_receiver/notify.py, lib/logitech_receiver/settings_templates.py
=> device: add notify module to logitech_receiver

.pre-commit-config.yaml, lib/logitech_receiver/__init__.py, lib/logitech_receiver/descriptors.py, lib/logitech_receiver/settings_templates.py
=> fix problem with lots of onboard profiles

lib/hidapi/hidapi.py, lib/hidapi/hidconsole.py, lib/hidapi/udev.py, lib/logitech_receiver/base.py, lib/logitech_receiver/common.py, lib/solaar/i18n.py
=> Remove unnecessary calls of del

lib/solaar/ui/diversion_rules.py
=> Refactor diversion rules

lib/logitech_receiver/diversion.py, tests/logitech_receiver/test_diversion.py
=> Simplify diversion

.github/workflows/tests.yml, lib/hid_parser/__init__.py, setup.py
=> Drop support for end-of-life Python 3.7

docs/implementation.md
Gives an overview of the main components of Solaar and their connections.
Fixes #2481
=> docs: Add high-level graph of components

.github/workflows/tests.yml, lib/hidapi/hidapi.py, lib/logitech_receiver/diversion.py, lib/solaar/dbus.py, tests/logitech_receiver/test_device.py, tests/logitech_receiver/test_receiver.py
=> Fix macOS compatibility and reenable CI tests

lib/logitech_receiver/device.py, lib/logitech_receiver/receiver.py, lib/solaar/cli/__init__.py, lib/solaar/listener.py, tests/logitech_receiver/test_device.py
- Explicitly pass low level dependency to simplify testing with fakes.
Related #1097
=> refactor: Creation of devices

.github/workflows/gh-pages.yml
Avoid draft documentation from being published.
=> Publish GitHub pages only on push to master

lib/logitech_receiver/notifications.py, tests/logitech_receiver/test_notifications.py
=> notifications: Introduce unit tests

lib/logitech_receiver/common.py, lib/logitech_receiver/device.py, lib/logitech_receiver/hidpp10.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/hidpp20_constants.py, lib/logitech_receiver/receiver.py, lib/logitech_receiver/special_keys.py, lib/solaar/cli/show.py, tests/logitech_receiver/test_common.py, tests/logitech_receiver/test_hidpp10.py, tests/logitech_receiver/test_hidpp20_complex.py, tests/logitech_receiver/test_hidpp20_simple.py
Refactors NamedInts
- FEATURE_FLAG
- FIRMWARE_KIND
- CID_GROUP
- CID_GROUP_BIT
into enum classes.
=> Replace NamedInts from hidpp20 constants

docs/i18n.md, lib/solaar/ui/about/model.py, po/nn.po
Should be merged after the Norwegian Bokmål patch, and will then have a minor conflict in model.py
=> i18n: Updated Norwegian Nynorsk (nn)

lib/logitech_receiver/receiver.py
Fixes #2674 
Fix errors like during init:
```
Exception ignored in: <function Receiver.__del__ at 0x7fe4742a37e0>
File "/usr/lib/python3.12/site-packages/logitech_receiver/receiver.py", line 146, in __del__
self.close()
File "/usr/lib/python3.12/site-packages/logitech_receiver/receiver.py", line 138, in close
handle, self.handle = self.handle, None
^^^^^^^^^^^
AttributeError: 'BoltReceiver' object has no attribute 'handle'
2024-11-06 09:55:24,035,035    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw7', bus_id=3, vendor_id='046D', product_id='C548', interface=2, driver='hid-generic', manufacturer=None, product=None, serial='', release=None, isDevice=None, hidpp_short=True, hidpp_long=True)
Traceback (most recent call …
```
=> fix BoltReceiver, Ex100Receiver __init__

lib/solaar/gtk.py
solaar creates a tempfile. In cli-mode doesn't delete in on close.
This minimal patch fixes this so that the tempfile gets deleted on cli-mode too.
=> delete tmpfile on close for cli

lib/logitech_receiver/base_usb.py, tests/logitech_receiver/test_base_usb.py
Refactor get_receiver_info. Replacing data structure of known receivers to avoid for loop, when an efficient dictionary lookup is possible.
Related #2273
=> Speedup lookup of known receivers

lib/logitech_receiver/diversion.py
Add BTN_SIDE and BTN_EXTRA to the mouseclick actions to support back and forward clicks. Not sure if this this applies to all Logitech devices; based it off the inputs that the mx master 2s supports.
=> settings: add back and forward mouseclick actions

Release_Notes.md, lib/hidapi/hidapi_impl.py, lib/logitech_receiver/diversion.py, lib/solaar/cli/show.py, lib/solaar/gtk.py
Use hidapi on macOS to communicate with Logitech peripherals connected via Bluetooth. This brings macOS device support on the same level as Linux.
Tested with MX Keys and MX Master 3S.
Fixes #2729
=> macOS: Add support for Bluetooth devices

lib/logitech_receiver/receiver.py, tests/logitech_receiver/test_receiver.py
=> receiver: Test data extraction of responses

lib/logitech_receiver/notifications.py, tests/logitech_receiver/test_notifications.py
=> Refactor notification handling

lib/hidapi/hidapi_impl.py, lib/hidapi/udev_impl.py
Logger enabled checks clutter the code unnecessarily. The checks are now handled in a custom logger class. Eventually they can be completely removed in the future.
Related #2664
=> hidapi: Remove outdated logger enabled checks

lib/logitech_receiver/desktop_notifications.py, lib/solaar/ui/desktop_notifications.py, tests/logitech_receiver/test_desktop_notifications.py, tests/solaar/ui/test_desktop_notifications.py
@MattHag Some tests were failing when run in a setting where desktop notifications are available.
=> testing: upgrade desktop notifications tests to take notifications availability into account

lib/logitech_receiver/hidpp20.py
Replace ButtonBehaviors and ButtonMappingTypes with IntEnum.
Related #2273
=> hidpp20: Remove dependency to NamedInts

.gitignore, lib/hidapi/hidapi_impl.py
If VID and PID are both zero, the device is highly unlikely to be HID++ capable. On an Apple Silicon Mac, there are a lot of internal HID class devices on bus ID 0x0, none of which are what we are looking for. In both cases we shouldn't even attempt to open the devices at all.
Not all HID class devices found on the system can be opened, `open_path()` will fail with an unhandled exception `IOHIDDeviceGetReport failed: (0xE00002C7) (iokit/common) unsupported function`. That has been fixed as well.
Update gitignore to include common junk files generated by macOS, and pipenv config which this project doesn't use.
=> Handle device open exceptions in hidapi and skip unsupported devices

lib/solaar/i18n.py
=> Fix invalid locale error

lib/hidapi/hidconsole.py, lib/logitech_receiver/common.py, lib/logitech_receiver/device.py, lib/logitech_receiver/diversion.py, lib/logitech_receiver/hidpp20.py, lib/logitech_receiver/listener.py, lib/logitech_receiver/settings_templates.py, lib/logitech_receiver/special_keys.py, lib/solaar/cli/probe.py, lib/solaar/cli/show.py, lib/solaar/cli/unpair.py, lib/solaar/i18n.py, lib/solaar/ui/config_panel.py, lib/solaar/ui/icons.py, lib/solaar/ui/rule_actions.py, lib/solaar/ui/rule_conditions.py, lib/solaar/ui/window.py
Rebased #2597 since it hasn't been updated in a while now. Commit has been attributed to the original author.
=> Rewrote string concatenation/format with f strings

docs/i18n.md
Serbian translation isn't mentioned in the docs even though it exists.
I checked the commit history and attributed correctly.
=> docs(i18n): mention Serbian translation

.github/workflows/tests.yml, Makefile
python 3.13 brings pygobject >= 3.52.1 which requires libgirepository 2.0. Add gobject-introspection has libgirepository-2.0-dev does not depends on it and it is required by PyGObject.
Closes #2857.
=> Fix ubuntu github CI

.github/workflows/tests.yml
This avoids cancelling the python 3.8 test when the python 3.13 one has failed.
=> Fix github workflow stopping all matrix jobs when one of them fails

lib/logitech_receiver/device.py
The Flag enum was applied the value method twice. remove the value method call from the set_flag_bits in  device.py. There is no such value call in receiver.py set_flag_bits in the same commit so I believe this was a mistake.
With this fix the LX7 mouse is properly enumerated over a Logitech C-BT44 Receiver (seen as EX100, compatible 27MHz FastRF protocol)
Close #2850.
Fixes: 72c9dfc5 Remove NamedInts: Convert NotificationFlag to flag
=> device: Fix listing of hidpp10 peripherals

lib/logitech_receiver/receiver.py
Fix error concatenating bytes with a string.
It seems that adding "00" to the bytes value has no more use, so I remove it.
Closes #2855.
Fixes: 5e0c85a6 receiver: Refactor extraction of serial and max. devices
=> device: Fix listing hidpp10 devices - bytes vs string concatenation

.github/workflows/tests.yml
=> GitHub CI: Disable latest Python tests on macOS
