pwr-Solaar/Solaar

po/es.po

Now affecting just the proper file

Added Spanish Translation

---

docs/devices.md
docs/devices/m570.txt

Just picked up this mouse yesterday and discovered this utility today.
I'm unsure about my output from `solaar show`.

Add M570 Trackball detail

---

docs/devices.md

Add Nano receiver 046d:c52b in the supported devices. 
Also, FN swap works on K400.

Update devices.md with K400 Touch

---

lib/logitech_receiver/descriptors.py

The new_fn_swap works on the K400 Plus model.

Add setting for K400 Plus keyboard

---

lib/hidapi/udev.py

* from_device_number raises an exception if no device found, rather than
returning None. So, instead of checking the result, catch the exception.
* Use Attributes.get() method instead of checking containment and using the
index operator. This is really the only correct way, see rhbz#1267584.
Effect of the changes:
Previously, if no device was found this method would raise an exception.
Now it returns None instead.
Previously, this method read a value for every key in what udev lists as
its "available" attributes, which was expensive and potentially destructive.
That was how the 'key in attributes' expression was implemented.
Now, the method only reads the key of interest.
Reason for noticing all these problems:
In pyudev-0.18 the Attributes class is fixed, and no longer has the [] …

Fix some bugs in udev.get_indexed_string.

---

README.md

Authorship from:
https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-misc/solaar/ChangeLog?revision=1.12&view=markup#l49

readme Gentoo link updated with official package

---

docs/devices.md
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/config.py
lib/solaar/ui/config_panel.py

Adds support for the MX Master (#208), supporting DPI adjusting and the Smart Shift feature. Some details:
- Adds the ability to R/W choices to features (HID 2.0+)
- Smart Shift supports any value from 0x01 to 0xff, I have limited the choices to what the Logitech software allows.

Support mx master

---

po/tr.po

Hi folks,
Can you please, add Turkish translation file?

add turkish translation file

---

po/pt_BR.po

Let me know if I need to change anything.

Added brazilian portuguese translation

---

docs/i18n.md
lib/solaar/ui/about.py
po/pt_BR.po

Some pt-br translation where ambiguous or too missing 'not' statement.
Add original translator, Mr. Drovetto, to the documentation.
Made small improvements to PR #242 

pt-br: Improve translations

---

README.md

Fixes #261
Applied @ellisistfroh suggestion

README nano receiver broken link

---

docs/installation.md

Minor correction on readme file.

Update installation to point correct rules file

---

README.md
share/applications/solaar.desktop

Add French translation on desktop file

---

packaging/debian/solaar.udev
rules.d/42-logitech-unify-permissions.rules

Add receiver to udev rules

---

docs/devices.md
docs/devices/k780.txt
lib/logitech_receiver/descriptors.py

Device information provided by @faassen
Tests provided by @ralphdd
relates to #298

K780 add descriptor support and device information

---

docs/devices.md
docs/devices/M510_HIDppV4.5.txt
docs/devices/m560.txt

Contribution from @mhalano 
relates to #226 

M560 device info contributed by @mhalano

---

docs/devices/mk220-new.txt
lib/logitech_receiver/descriptors.py

Thanks to @FabioBeneditto for providing information.
Depends on #337
fixes #222

MK220 Combo descriptor for Mouse M150 and new docs

---

docs/devices.md
docs/devices/mk520.txt

Wireless Keyboard K520  HID++ 1.0
Wireless Mouse M310  HID++ 2.0
Fully functional on Solaar at this point.

MK520 Combo - Documentation

---

docs/devices.md
docs/devices/m185_new.txt
docs/devices/m185_old.txt
lib/logitech_receiver/base_usb.py
lib/logitech_receiver/common.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py
lib/solaar/cli/show.py
packaging/debian/solaar.udev
rules.d/42-logitech-unify-permissions.rules

Added basic support for M185 and logs of two hardware versions

Basic support for M185 mouse

---

README.md
docs/devices.md

Hi there. I was going through the typical docs and ran into couple of dead links in `devices.md`. I went on Logitech website to look for something to replace them with... and I found nothing. I go ahead and remove them. The other links are still okay. Thanks.

Remove dead links

---

docs/devices/mk270.txt
lib/logitech_receiver/descriptors.py

*** This PR depends on #337 
Adds support for MK 270 Combo. 
K270 non unifying
M185 non unifying (older version than #337)
fixes #234

Mk270 Combo information and descritptors

---

docs/devices/mk240-nano.md

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>

Information and comments regarding Logitech MK240 NANO Combo

---

docs/devices.md

This commit adds the Logitech MX Ergo to the list of supported devices.

Update devices.md with MX Ergo trackball

---

lib/solaar/ui/icons.py

This pull request provides support for the default icon theme in Linux Mint (tested in Cinnamon edition). See the example screenshot below.

Added support for MintX icon set (for Linux Mint integration)

---

lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/__init__.py

This avoids solaar crashing when used with the MX Ergo.

Improve trackball support

---

docs/devices.md

Tested on hardware (K400 Plus) with [manual installation](https://pwr.github.io/Solaar/installation.html) from `master`.

Add K400 Plus

---

docs/devices.md
lib/logitech_receiver/descriptors.py

I have a Wireless Mouse M235, so would like to update the info here ;)

Update Data of Wireless Mouse M235

---

lib/solaar/gtk.py
lib/solaar/ui/icons.py
setup.py

When I tried to get solaar up and running, I noticed a few mistakes. This series fixes some boilerplate stuff and add comments to the sources.

get developer install (pip -e) running

---

lib/logitech_receiver/descriptors.py

“Multi-Device” and not “Solar”

Name for K780

---

packaging/debian/substvars.theme.ubuntu

Add gnome-icon-theme as an acceptable dependency for icons

---

po/zh_TW.po

Fix zh_TW translation (nplural=1)

---

lib/logitech_receiver/descriptors.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/show.py

Added status info on features MOUSE_POINTER, VERTICAL_SCROLLING, HI_R…ES_SCROLLING, POINTER_SPEED and LOWRES_WHEEL to solaar show.
Renamed functions for HI_RES_SCROLLING and LOWRES_WHEEL features for consistency.

Added status info print and rename some functions

---

lib/hidapi/udev.py

@mfulz and @tomswartz07 could you confirm this works for both of you?

udev: fix c52b + MX Master

---

lib/logitech_receiver/settings.py

Fixes #328
Fixes #356
Fixes #545

Fix reading and storing DPI in config settings

---

po/de.po
po/el.po
po/es.po
po/fi.po
po/fr.po
po/hr.po
po/it.po
po/pl.po
po/ro.po
po/ru.po
po/solaar.pot
po/sv.po
po/tr.po
setup.py

- Update French translation by David Geiger <david.david@mageialinux-online.org>
- Update version into setup.py file
- Update version in fr.po

po formatting updates

---

docs/devices/craft.txt
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/status.py

only basic support
issues so far:
- when plugged in, wrong battery status `discharging` level=0
- toggle FN does not work: `read/write operation failed`
- a lot of warnings of unkown FEATURE_SET notifications
```
WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4066,Keyboard)>: unrecognized Notification(1,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
```

Basic support for craft keyboard

---

lib/logitech_receiver/notifications.py
lib/solaar/ui/tray.py

Fix indicator tooltip (duplicate Solaar line, python list instead of battery status).

Fix battery status notification parsing. 

---

lib/logitech_receiver/notifications.py

Signed-off-by: Filipe Laíns <lains@archlinux.org>

notifications: add missing protocol names

---

docs/devices.md

Simple doc update to show that Solaar supports changing DPI for the Logitech Anywhere MX 2.

Update devices.md for Anywhere MX 2 - R/W DPI

---

docs/devices.md

Add M330 under the Nano section.

Update devices.md for M330

---

README.md
docs/index.md

@Lekensteyn 
I made a ppa repository which when you make a change in github automatically syncs and builds debs packages.

docs: readme: add new ppa

---

docs/devices/mx-master-3.txt

Added an information text file with the show command data about the MX Master 3 mouse

docs: devices: add Mx Master 3

---

docs/devices.md
docs/index.md
docs/installation.md

I've done some updates to three documentation pages to better describe what solaar is, what it can do, and what it can't do; what devices are handled; and how to download and run from the download directories.
I think I have some good instructions on installing. I ran into several of the usual issues using pip to install into system directories, but I think I've got them licked.
This pull request concerns https://github.com/pwr-Solaar/Solaar/issues/591

updates to documentation

---

docs/usb.ids.txt

Updated the USB IDs list as of November 2019

Update USB IDs list to 2019

---

lib/logitech_receiver/hidpp20.py
lib/solaar/cli/show.py

Signed-off-by: Filipe Laíns <lains@archlinux.org>

hidpp20: features: add BATTERY_VOLTAGE (0x1001) support

---

docs/devices.md
docs/devices/k800-new.txt
lib/logitech_receiver/descriptors.py

devices: Add new variant of K800 keyboard
docs: Add K800 new variant to supported
resolve #576

Add support of new variant of K800 keyboard

---

setup.py

Signed-off-by: Filipe Laíns <lains@archlinux.org>

setup.py: drop python 2 support

---

docs/installation.md

To go along with the changes to setup.py

docs: minor changes to installation.md to eliminate python2 support

---

docs/_config.yml

The version there is currently 0.9.2, which is wrong.
0.9.2 also shows up in the translations, but I'm not sure whether to change them.

update version in docs/_config.yml to 1.0.1

---

ChangeLog

Add section at beginning of changelog for commits from 1.0.1 to 11 February 2020.

docs: update changelog to 11 February 2020 commits

---

docs/index.md

I forgot to add this commit to PR #666

docs: add information on --windows flag and rewrite other bits of index.md

---

lib/solaar/cli/__init__.py
lib/solaar/cli/probe.py

I wrote this code to dump receiver registers. 
I don't know if it is a good idea to add it to Solaar.  I created this PR for discussion.
Addresses #74

cli: add probe command to show receiver register information

---

docs/index.md
lib/solaar/gtk.py
setup.py
share/autostart/solaar.desktop

Also adjust the installed autostart .desktop file to hide the main window.
FIxes #701

make solaar default be to show the main window when starting the UI

---

ChangeLog

update ChangeLog for changes up to 15 March 2020

docs: Update ChangeLog

---

lib/logitech_receiver/base_usb.py
lib/solaar/cli/show.py

Also adjust max pairing for C517 receiver

Handle receivers with no firmware information

---

release.sh

Signed-off-by: Filipe Laíns <lains@archlinux.org>

release.sh: initial script

---

lib/solaar/cli/show.py
lib/solaar/ui/window.py

Add more defensive measure for devices and receivers with no firmware information

ui: handle devices and receivers with no firmware information

---

docs/_config.yml
lib/solaar/__init__.py

I didn't change the version numbers in the translation files.  My guess is that these should not be changed.
Fixes #725 
Fixes #669

release: update remaining version 1.0.1 to 1.0.2-rc1 where needed

---

po/pl.po

Added some missing polish translations and fixed typos in existing.
Unfortunately, my newest version of POEdit reformatted whole file.

Improve polish translations

---

lib/logitech_receiver/base_usb.py
lib/logitech_receiver/descriptors.py

As reported by @muzena 
Fixes #716

fix up c517 receiver and add four old devices (MK300, S510, LX5, M30)

---

lib/solaar/ui/icons.py

ui: add setuptools global install share directory to icon directories

---

docs/devices.md

Also change wording at beginning a  bit.
Fixes #753 
Fixes #755 
Fixes #756

docs: add K600 TV, new M350, MX Keys to devices.md and improve wording in it

---

lib/logitech_receiver/status.py

Some devices don't provide discharge level when charging.  When this happens, infer battery level (roughly) from charging information.
Fixes #750

heuristic inference of battery level when charging and no discharging information available

---

ChangeLog

release 1.0.2rc2

---

docs/installation.md

The installation documentation was a bit unclear on when the requirements needed to be done, which made it look as if downloading from the repository required updating your system.  I fiddled with the order of sections in the installation documentation and modified some of the wording to try to make what is needed clearer.

upgrade installation documentation

---

po/fr.po

Update again French translation

---

ChangeLog
docs/_config.yml
lib/solaar/__init__.py
setup.py

release 1.0.2

---

docs/devices.md
lib/logitech_receiver/base_usb.py
rules.d/42-logitech-unify-permissions.rules

receiver: add c53d as a Lightspeed receiver

---

docs/features.md
docs/usage.md

Update features.md to reflect current implementation status.
Also add a section on how to implement a feature.
Also a minor update to usage.md

update features.md and usage.md

---

lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/status.py
lib/solaar/cli/show.py
lib/solaar/ui/window.py

Depends on (incorporates) PR #789
Fixes #724 
Fixed #570 
Does not include processing of battery voltage notifications.

show battery voltage in main window

---

lib/solaar/ui/window.py

ui: remove maximum window size

---

lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

This feature is not a simple bit flag, but can be handled much as if it is.

receiver: fix k375s Fn inversion

---

lib/solaar/gtk.py

misc: dump threads on SIGINT

---

lib/logitech_receiver/settings_templates.py
lib/solaar/cli/config.py

Fixes #845 
Config was always determining all the settings for the device.  This is not needed if only one setting is being printed or changed.

cli: make config faster

---

docs/features.md
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/config_panel.py

receiver: add setting for MULTIPLATFORM and DUALPLATFORM feature

---

lib/logitech_receiver/base.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

Changehost

---

lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/receiver.py

receiver: use report rate feature if available to determine polling rate

---

lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/config_panel.py

fixes for non-persisted settings and related changes

---

docs/features.md
lib/logitech_receiver/settings_templates.py

receiver: add mode and inversion settings for feature THUMB_WHEEL

---

lib/hidapi/udev.py

hidapi: fix infinite loop on some write errors

---

po/nb.po
po/solaar.pot

Note that I have not been able to run Solaar with this translation, due to some unrelated error.

Translation for Norwegian Bokmål

---

lib/solaar/listener.py

receiver: ignore DJ pairing notifications

---

docs/installation.md

docs: add instructions on translations to docs/installation.md

---

po/sv.po

Updated translations for Swedish.
Checked in Ubuntu 20.04 LTS, and it loads as it should.

po: update translation for Swedish

---

po/fr.po

Update French translation for 1.0.3rc2 release

---

po/nb.po

Branched from a clean new fork, and with a single commit.

po: update translation for Norwegian Bokmål

---

po/nn.po

Branched from a clean fork, after #887, and with a single commit.

po: add translation for Norwegian Nynorsk

---

po/da.po

Danish is difficult, so expect requests for fixes.

po: add translation for Danish

---

lib/solaar/listener.py
lib/solaar/ui/pair_window.py
lib/solaar/ui/window.py

ui: use ngettext for translatable strings with number dependencies

---

po/da.po

po: update translation for Danish

---

po/nn.po

po: update translation for Norwegian Nynorsk

---

po/da.po
po/nb.po

po: update translation for Norwegian Bokmal

---

po/solaar.pot

po: update pot-file

---

RELEASE.md

Small cleanup of the RELEASE.md page.
This page is outside the docs folder.

linted release page

---

docs/devices.md
lib/logitech_receiver/base_usb.py
rules.d/42-logitech-unify-permissions.rules

receiver: add lightspeed receiver c545

---

po/pt.po

This was provided a while ago on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761589; it’s presumably missing translations for newer messages.

po: Add Portuguese translation

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/status.py
lib/solaar/listener.py

keep better track of battery voltage for GUI

---

docs/devices.md
lib/logitech_receiver/base_usb.py
rules.d/42-logitech-unify-permissions.rules

receiver: add lightspeed receiver c541

---

lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/receiver.py
lib/solaar/listener.py

Discovered looking at issue #915

check that device can retrieve host names before trying that; downgrade unpair warnings to info messages

---

lib/solaar/i18n.py

misc: ignore exceptions when trying to set locale

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings.py

receiver: use DJ connection notifications to set device active status

---

docs/features.md
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

The number of arguments to the settings templates convenience functions was growing so large that calls to them had their arguments one per line, making them harder to read; the conveniene functions were growing large; and adding a new argument required changes to multiple convenience functions.   This PR eliminates the convenience functions and also simplifies the settings classes.  The net result is that settings templates are shorter (because the label and description arguments are no longer needed) but perhaps slightly more complex (because a simple setting template needs to set up the three classes directly).  Splitting the arguments into three groups does make the setting templates easier to understand, though.

receiver: simplify settings interface

---

lib/logitech_receiver/device.py
lib/logitech_receiver/notifications.py

receiver: remove spurious part of special handling for ex100 receiver

---

docs/index.md
lib/logitech_receiver/device.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/pair.py
lib/solaar/listener.py
lib/solaar/ui/window.py

Better strings in UI; add node path to UI; tolerate errors when finding device node; allow non-unifying connection notifications

---

lib/logitech_receiver/settings_templates.py
lib/solaar/ui/window.py

The display strings for settings needed regularization.
The settings were not displayed in a reasonable order.

ui: improve display strings and ordering for settings

---

lib/logitech_receiver/settings_templates.py

ui: show all host choices

---

lib/solaar/cli/pair.py

cli: ignore DJ pairing notifications in CLI pair command

---

docs/capabilities.md
docs/devices.md
docs/features.md
docs/index.md
docs/installation.md
docs/usage.md
lib/hidapi/udev.py
lib/logitech_receiver/base.py
lib/logitech_receiver/base_usb.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py
lib/solaar/cli/__init__.py
lib/solaar/configuration.py
lib/solaar/listener.py
lib/solaar/ui/window.py
rules.d/42-logitech-unify-permissions.rules

Fixes #268 
Find bluetooth connected devices.
Talk to bluetooth connected devices.
Move information for USB-connected and bluetooth-connected devices to descriptors.py

support bluetooth-connected devices

---

lib/logitech_receiver/base_usb.py
lib/logitech_receiver/descriptors.py
lib/solaar/listener.py
lib/solaar/ui/__init__.py

Add G700s USB information and allow specifying USB interface number in descriptors

---

lib/logitech_receiver/settings_templates.py

settings_templates: typo

---

lib/solaar/configuration.py
lib/solaar/ui/config_panel.py

ui: add lock icon to control whether individual settings can be changed

---

docs/devices.md

docs: fix typos in devices.md

---

lib/logitech_receiver/common.py
lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/status.py

device: implement UNIFIED_BATTERY feature

---

lib/solaar/ui/config_panel.py

Addresses a problem pointed out by @pfps (see https://github.com/pwr-Solaar/Solaar/pull/980#issuecomment-715313399).

Create attributes to access children in settings with multiple items

---

docs/rules.md
lib/logitech_receiver/diversion.py

See https://github.com/pwr-Solaar/Solaar/pull/998#issuecomment-727216501

Add MouseClick diversion rule

---

docs/installation.md
setup.py

install: update and document new dependencies

---

setup.py
share/solaar/metainfo.xml

doc: add app metainfo file

---

docs/installation.md
lib/logitech_receiver/base.py
lib/solaar/cli/show.py
lib/solaar/ui/tray.py
lib/solaar/ui/window.py

Fixes #995 
Several fixes to address problems when devices or receivers disconnect.

Disconnect

---

lib/logitech_receiver/status.py
lib/solaar/listener.py

device: push device settings when device is active after suspend

---

docs/installation.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py
setup.py

rules: remove use of pynput

---

lib/logitech_receiver/hidpp10.py
lib/solaar/ui/icons.py

receiver: add remote device type

---

lib/logitech_receiver/diversion.py

rules: only activate rules if X11 is running

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py

settings: add setting to divert G keys and handle in rules

---

docs/index.md

docs: remove pointer to SUSE package as it is very old

---

po/pl.po

po: Update translation for Polish

---

lib/solaar/gtk.py
lib/solaar/ui/icons.py
lib/solaar/ui/tray.py

ui: add option to not use battery icons for tray icon

---

po/fr.po

Update French translation for 1.0.4 release

---

lib/solaar/ui/about.py

Update about.py to bump copyright years

---

po/cs.po
po/da.po
po/de.po
po/el.po
po/es.po
po/fi.po
po/fr.po
po/hr.po
po/it.po
po/nb.po
po/nl.po
po/nn.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/solaar.pot
po/sv.po
po/tr.po

Also update the translation files for the new strings in Solaar.

i18n: update german and italian translations

---

lib/logitech_receiver/settings.py
lib/solaar/cli/__init__.py
lib/solaar/cli/config.py

cli: set keyed settings with config

---

lib/solaar/cli/pair.py

cli: fix bug in finding receiver to pair

---

lib/solaar/cli/__init__.py

cli: fix up help messages for selecting devices and receivers for CLI commands

---

po/fr.po

Update French translation for 1.0.5 release

---

lib/logitech_receiver/settings_templates.py

settings: add quirk to not set up host mode on G915 TKL keyboard

---

lib/solaar/cli/config.py

cli: fix config check against choices

---

lib/logitech_receiver/device.py

device: don't always use long messages for protocol 1.0

---

docs/installation.md

docs: update package dependencies

---

lib/logitech_receiver/hidpp20.py

device: set current host name if not current host

---

lib/logitech_receiver/device.py
lib/solaar/configuration.py
lib/solaar/listener.py

device: always get persister when setting up settings

---

lib/solaar/listener.py
lib/solaar/ui/__init__.py

receiver: handle exception when device is not available while being added

---

lib/solaar/ui/icons.py

ui: correctly set icon theme value when regular battery icons are missing

---

lib/logitech_receiver/diversion.py

Fixes #1121 based on the discussion

Match WM_CLASS also for process matching in rules

---

lib/logitech_receiver/base_usb.py
lib/logitech_receiver/receiver.py

receiver: receiver c52e does not unpair

---

docs/capabilities.md
docs/index.md

docs: describe how to install a system tray for Gnome

---

release.sh

Need for changes in github API

misc: update release.sh

---

lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp10.py

device: convert HID++ 2.0 device kinds to enhanced HID++ 1.0 kinds

---

lib/logitech_receiver/base_usb.py

The title speaks for itself: Add support for the g pro x superlight.

Support logitech g pro x superlight

---

docs/installation.md
lib/logitech_receiver/settings_templates.py

settings: fix fake divert gkeys read to return byte string

---

docs/rules.md
lib/logitech_receiver/diversion.py

rules: add checks for empty process name and class

---

lib/logitech_receiver/base.py
lib/logitech_receiver/listener.py

... so that threads do not receive response for a different request
Fixes #1125

receiver: serialize requests per handle 

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: add rule condition for process under mouse

---

docs/index.md
lib/solaar/cli/show.py

show battery information for unified battery feature

---

lib/hidapi/udev.py

hid: add debug message when potential device found

---

lib/logitech_receiver/base.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py
lib/solaar/ui/window.py

use 0xFF for direct-connected devices

---

lib/logitech_receiver/base.py
lib/logitech_receiver/device.py
lib/solaar/cli/show.py

device: fix determination of SW ID for HID++ 2.0 feature requests

---

lib/logitech_receiver/settings.py

settings: don't use time_ns so as not to require Python 3.7

---

lib/solaar/ui/config_panel.py

ui: correctly determine setting box in change_click method

---

lib/logitech_receiver/base.py
lib/solaar/listener.py

listener: handle fake Nano connection notifications

---

docs/usage.md
lib/logitech_receiver/base_usb.py

receiver: mark Nano receiver C52F as not unpairing

---

lib/solaar/ui/tray.py

ui: better computation of tray index when adding devices

---

lib/solaar/ui/tray.py

ui: better code for adding devices to tray menu

---

docs/capabilities.md
docs/index.md
docs/usage.md
lib/logitech_receiver/base.py
lib/logitech_receiver/base_usb.py
lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/status.py
lib/solaar/cli/pair.py
lib/solaar/cli/probe.py
lib/solaar/listener.py
lib/solaar/ui/pair_window.py

support Bolt receiver

---

lib/logitech_receiver/settings.py

device: catch errors when applying settings

---

docs/rules.md

docs: better information on diverting keys, etc., to trigger rules

---

docs/index.md
lib/solaar/gtk.py
lib/solaar/ui/tray.py

ui: add option to specify use of explict tray icon files and their size

---

lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

* implemented a switch for swapping between smooth scrolling and ratchet for the crown

Smooth scroll for crown

---

lib/logitech_receiver/notifications.py

don't perform on-screen notifications for wireless device status notifications

---

lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp10.py

device: add descriptor for Logitech PRO X Wireless Gaming Headset

---

lib/logitech_receiver/hidpp20.py
lib/solaar/ui/window.py

ui: display percentage estimates from battery voltage

---

lib/logitech_receiver/device.py

device: check for uninitialized protocol when pinging

---

lib/logitech_receiver/descriptors.py

reformat descriptors.py and add G512 and G402

---

lib/solaar/ui/icons.py

change battery percentage boundaries

---

lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings.py
lib/solaar/cli/config.py
lib/solaar/gtk.py
lib/solaar/ui/config_panel.py
lib/solaar/ui/window.py

add Set rule action to set device settings

---

lib/logitech_receiver/descriptors.py

device: add G733 headset

---

lib/solaar/ui/tray.py

ui: hide system tray icon when there are no devices to control

---

lib/logitech_receiver/device.py
lib/logitech_receiver/diversion.py
lib/logitech_receiver/hidpp20.py

better implementation of gestures and locking to prevent duplication of work

---

lib/logitech_receiver/diversion.py

rules: check for xtest and disable modifier checking if not available

---

lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py

Fixes #1394
at least so far as it can be fixed

rules: track M keys and MR keys for use in rules

---

lib/logitech_receiver/descriptors.py

device: add G815 keyboard and MX518 mouse

---

lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings_templates.py

fix bug in unpacking M and MR key notification; add settings for M-Keys and MR-Key LEDs

---

lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings.py

No GUI for these yet.
The arguments are like the arguments for changing device settings.
For example the following rule in rules.yaml would input an a when the Host Switch Channel 2 key is pressed, but only if the caps lock key is disabled.
```
---
- Key: [Host Switch Channel 2, pressed]
- Setting: [null, disable-keyboard-keys, 1, false]
- KeyPress: [a]
...
```

add rule condition to check settings of devices

---

lib/logitech_receiver/notifications.py

receiver: dispose of no-op notifications quickly

---

lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py

device: add G9 Laser Mouse

---

lib/solaar/listener.py

push settings to all devices on resume

---

lib/logitech_receiver/settings_templates.py

settings: fix bug in speed-change setting

---

po/de.po
share/autostart/solaar.desktop

This PR will:
- add German translation for some new strings of PR's that got merged during the last few days
- improves some strings in the existing German translation
- adds a translated comment to the solaar.desktop example file

update German translation

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

TestBytes GUI

---

lib/solaar/cli/config.py
lib/solaar/ui/__init__.py

make solaar config changes also take effect in solaar ui if running

---

lib/solaar/ui/diversion_rules.py

GUI for Setting rule

---

lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/show.py
lib/solaar/ui/config_panel.py

add setting to divert gestures

---

lib/solaar/ui/tray.py

ui: allow tray icon to scroll whenever at least two devices

---

lib/logitech_receiver/base_usb.py
lib/logitech_receiver/settings_templates.py

Backlight and K810

---

lib/logitech_receiver/base_usb.py

device: support C542 receiver for M190 mice

---

docs/i18n.md
po/solaar.pot
po/zh_CN.po

I updated the zh_CN translation strictly following the [translation guide](https://pwr-solaar.github.io/Solaar/i18n). However, I had noticed that most translators never follow the guide like me, so please let me know if restricting the modification range is needed.

Update zh_CN translation

---

lib/logitech_receiver/diversion.py

rules: graceful degredation when no keymap available

---

docs/index.md
docs/installation.md
lib/logitech_receiver/diversion.py

rules: handle missing libX11 more gracefully and document dependency

---

lib/logitech_receiver/common.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/config.py

fix bugs in config command

---

lib/solaar/cli/config.py
lib/solaar/listener.py

handle inability to set up GTK application in Solaar config

---

lib/logitech_receiver/diversion.py

rules: fix problems when X11 is not available

---

lib/logitech_receiver/settings.py
lib/solaar/configuration.py
lib/solaar/ui/config_panel.py

Json has limitations which makes Solaar code more complex.  Using YAML allows for better code in the rest of Solaar.

change Solaar config file from json to yaml

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/status.py

device: use isDevice, not kind, to distinguish between devices and receivers

---

lib/logitech_receiver/descriptors.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/diversion_rules.py

Addresses #1560
add diversion setting for hires scroll wheel and fix information about lowres scroll setting
add recent diversion features to default list in rules UI

add diversion setting for hires scroll wheel

---

lib/logitech_receiver/diversion.py

rules: fix bug in xtest mouse scrolling

---

lib/logitech_receiver/descriptors.py

device: add G533 headset

---

lib/logitech_receiver/hidpp20.py

device: clear out fields for empty persistent remappable action

---

docs/rules.md
lib/logitech_receiver/diversion.py

rules: improve KeyPress action

---

po/tr.po

I have translated and corrected more words/sentences.
Cheers

update Turkish translation

---

lib/logitech_receiver/diversion.py

rules: don't add HI_RES wheel ecodes to evdev device codes

---

lib/logitech_receiver/base.py
lib/logitech_receiver/common.py
lib/logitech_receiver/diversion.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/config_panel.py

add packed range setting; add sidetone and equalizer setting templates

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: add depress and release options to KeyPress rule action

---

docs/installation.md
lib/solaar/ui/tray.py

document system tray library requirements better

---

lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/special_keys.py

device: fix no-output values for persistent key mappings

---

lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

fix problem with unusual PRA value from Craft in MacOS mode

---

lib/logitech_receiver/hidpp20.py

device: use correct Solaar functions for unified and voltage battery functions

---

docs/capabilities.md
docs/rules.md
lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py

settings: allow multiple keys for mouse gestures and dpi sliding

---

po/rs.po
po/solaar.pot

Hey there!
I took some time and translated your program to Serbian. Main problem is that I'm unable to compile 'rs.po' and it throws me this errors:
``/home/renato/Desktop/Solaar/po/rs.po:7: invalid nplurals value
/home/renato/Desktop/Solaar/po/rs.po:1632: a format specification for argument 'mak_count', as in 'msgstr[0]', doesn't exist in 'msgid_plural'
/usr/bin/msgfmt: found 4 fatal errors
``
Language file is added in po folder, fully translated and ready to be included in your project. Can someone compile it and add to bin?
Let me know the results!

po: Added Serbian translation

---

po/de.po

This matches the German language Logitech marketing material.

Use German word Gestentaste in translation

---

docs/devices/MX Keys Keyboard 408A.txt
docs/devices/Wireless Mouse Pebble M350 4080.txt
lib/logitech_receiver/device.py
lib/logitech_receiver/receiver.py
lib/solaar/cli/__init__.py
lib/solaar/cli/probe.py
lib/solaar/listener.py

support powerplay

---

docs/devices/ERGO M575 Trackball 4096.txt
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: save rules file even if there are no rules to save

---

.github/ISSUE_TEMPLATE/bug_report.md
lib/solaar/gtk.py

log messages to a temporary file

---

lib/solaar/ui/diversion_rules.py

ui: add description of rule components to rule editor

---

lib/logitech_receiver/settings_templates.py

settings: move rawXY patch to new code for both sliding dpi and mouse gestures

---

docs/index.md
docs/usage.md

documentation updates

---

docs/i18n.md
po/nb.po

Should be pretty complete, without some last minute changes to the base repo.

Translate Norwegian Bokmal

---

lib/solaar/ui/window.py

ui: change security tooltip for unencrypted wireless connections

---

docs/devices/G915 WIRELESS RGB Mechanical Gaming Keyboard 407E.txt
docs/devices/Lightspeed Receiver C541.txt
docs/devices/Wireless Keyboard K360 4004.txt
docs/devices/Wireless Mouse MX Master 4071.txt
lib/solaar/ui/config_panel.py

allow config panel to scroll

---

lib/logitech_receiver/diversion.py
lib/logitech_receiver/settings_templates.py

fix empty gesture rule bug

---

lib/logitech_receiver/descriptors.py

device: add G213 Gaming Keyboard

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: add later action

---

docs/devices/G733 Gaming Headset 0AB5.text
lib/solaar/configuration.py

use device name as backup for device model ID

---

lib/solaar/configuration.py

solaar: handle exceptions processing configuration file

---

lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/notifications.py

device: fix processing of HID++ 1.0 battery reports

---

docs/devices/MX Keys for Business B363.text
docs/devices/MX Master 3 for Business B028.text
docs/devices/Marathon Mouse M705 101B.txt
docs/devices/Nano Receiver C535.txt
docs/devices/Wireless Mouse M215 2nd Gen 401B.txt
lib/logitech_receiver/settings.py
lib/logitech_receiver/special_keys.py

settings: don't add non-existant key in raw xy processing

---

lib/solaar/ui/config_panel.py

ui: eliminate visual glitch when updating range settings

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings_templates.py

support smart shift ratchet switching

---

docs/installation.md
lib/solaar/cli/config.py
lib/solaar/configuration.py
lib/solaar/gtk.py

cli: don't defer saves in cli and don't require gtk in cli

---

setup.py

install: remove unnecessary dependency on typing_extensions

---

lib/solaar/ui/diversion_rules.py

ui: reduce standard size of rule editor window

---

po/es.po

The Spanish translation of the Solaar project is being updated.

po: Update es.po

---

docs/installation.md
lib/solaar/__init__.py
setup.py

dist: add git date to version information

---

.pre-commit-config.yaml

dist: fix flake8 URL

---

lib/solaar/__init__.py
lib/solaar/version.py
setup.py

dist: use git describe to get git version information

---

lib/solaar/ui/about.py

Added by translation made to the Solaar Project.

Update about.py (Spanish Translation Credits)

---

setup.py

dist: get commit from Ubuntu PPA directory name if no git information

---

.pre-commit-config.yaml
bin/solaar
lib/hidapi/udev.py
lib/solaar/cli/__init__.py
lib/solaar/gtk.py
lib/solaar/i18n.py
lib/solaar/listener.py
lib/solaar/ui/icons.py
lib/solaar/ui/notify.py
tools/hidconsole

@pfps Now it is more organized.
```
Check python ast.........................................................Passed
Check builtin type constructor use.......................................Passed
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Check Toml...........................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Fix double quoted strings................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed …
```

New release isortv4

---

.pre-commit-config.yaml
lib/hidapi/hidconsole.py
lib/hidapi/udev.py
lib/logitech_receiver/common.py
lib/logitech_receiver/diversion.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/listener.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/status.py
lib/solaar/cli/pair.py
lib/solaar/configuration.py
lib/solaar/listener.py
lib/solaar/tasks.py
lib/solaar/ui/__init__.py
lib/solaar/ui/config_panel.py
lib/solaar/ui/diversion_rules.py

Fixed: https://github.com/pwr-Solaar/Solaar/issues/1888

misc: update yapf version v3

---

.pre-commit-config.yaml

Updating .pre-commit-config.yaml.

Update .pre-commit-config.yaml : Release of pre-commit-hooks and flake8

---

.pre-commit-config.yaml

```
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check for merge conflicts................................................Passed
check yaml...............................................................Passed
check toml...........................................(no files to check)Skipped
debug statements (python)................................................Passed
fix double quoted strings................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
yapf.....................................................................Pas …
```

Update .pre-commit-config.yaml new version of flake8

---

docs/index.md
docs/rules.md

docs: update mouse gestures rules documentation

---

lib/logitech_receiver/common.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/show.py

device: more robust access to keyword exception fields

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings.py
lib/solaar/ui/config_panel.py

settings: only record changes of scroll wheel ratchet

---

po/pl.po
share/autostart/solaar.desktop

po-update.sh has been throwing "/bin/mktemp: too many templates" error since c2b4d5a8c82ad58d54bc3c132252e3871af0c245, so the PO file was updated with older (4e6f59c2ad373baa2352f1d791d931f54300f5c2) setup.py. I'm not sure if my new PO file is correct.

Update Polish translation

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

add parameter to thumb wheel tests

---

docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: add KeyIsDown condition

---

lib/solaar/listener.py
lib/solaar/ui/__init__.py

retry opening device if permissions are wrong

---

po/fr.po

Update French translation for 1.1.8 release

---

lib/logitech_receiver/settings_templates.py

settings: add setting for ADC power management

---

lib/logitech_receiver/descriptors.py

device: allow device descriptors without name and codename

---

lib/logitech_receiver/receiver.py
lib/solaar/ui/pair_window.py
lib/solaar/ui/window.py

improve pairing logic

---

docs/devices/Lightspeed Receiver C53A.txt
docs/devices/Lightspeed Receiver C53F.txt
lib/logitech_receiver/settings.py

read and check before writing range settings

---

lib/logitech_receiver/base.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/listener.py
lib/solaar/listener.py

support wired illuminated keyboard

---

lib/logitech_receiver/descriptors.py
lib/logitech_receiver/status.py
lib/solaar/ui/window.py

device: support G9x wired mouse

---

docs/devices/Logi Pop Keys B365.txt
docs/rules.md
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

rules: add Device rule

---

docs/devices/G304 Lightspeed Wireless Gaming Mouse 4074.txt
lib/logitech_receiver/device.py

device: get wpid for 28Mz devices from udev when enumerating

---

lib/logitech_receiver/diversion.py

rules: add Test condition for battery charging

---

docs/devices/MX Master 3 for Business B028.text
lib/solaar/gtk.py

better exit code on kill

---

docs/capabilities.md

A few minor changes, hopefully self-explanatory.

Fix punctuation and wording in capabilities.md

---

docs/features.md

I'm not 100% sure the backquotes around the filenames are necessary, so let me know if you would rather not include those.

Fix sentences and punctuation in features.md

---

lib/logitech_receiver/descriptors.py

Tested locally added G535 wireless gaming headset

Add support for G535 wireless gaming headset

---

lib/logitech_receiver/device.py

device: when finding name or codename ping if not known to be online

---

docs/devices/G502 Proteus Spectrum Optical Mouse C332.txt
docs/devices/G502 SE Hero Gaming Mouse C08B.txt
docs/devices/G815 Mechanical Keyboard C33F.txt
share/solaar/icons/solaar-symbolic.svg

add symbolic version of Solaar icon

---

lib/hidapi/hidconsole.py
lib/logitech_receiver/base.py
lib/logitech_receiver/descriptors.py
tools/scan-registers.sh

remove assertion on ping responses

---

lib/logitech_receiver/descriptors.py

device: add new ID for G733 Headset

---

po/fr.po

Update French translation for 1.1.9 release

---

lib/hidapi/udev.py

hidapi: retry open several times with short wait to allow for delay in setting up permissions

---

po/zh_TW.po

po: Update zh_TW Traditional Chinese locale

---

po/de.po
po/solaar.pot

Added some new German Translations

Updated German Translation

---

lib/hidapi/hidconsole.py
lib/logitech_receiver/descriptors.py
tools/scan-registers.sh

support for G500s mouse

---

lib/hidapi/hidconsole.py
lib/logitech_receiver/base.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py

device: improve determination of short or long messages

---

po/fr.po
po/solaar.pot

Update French translation (for release 1.1.10)

---

lib/solaar/ui/window.py

ui: update codename when device status changes

---

lib/logitech_receiver/base.py

device: add connection request failed error to expected ping responses

---

lib/logitech_receiver/descriptors.py

device: add support for MK550

---

docs/installation.md

docs: add instructions for pipx

---

docs/installation.md

Fixes #2141 by amending the installation directions.

docs: add note about other GTK system packages

---

lib/logitech_receiver/device.py
lib/solaar/cli/show.py
lib/solaar/listener.py

cli: handle NoSuchDevice exception when pinging device

---

docs/installation.md
lib/solaar/ui/icons.py
lib/solaar/ui/tray.py
lib/solaar/ui/window.py
setup.py

ui: better handling and installation of icons

---

docs/devices.md

docs: add wording about Logitech reusing model numbers

---

docs/devices/Wireless Mouse M325 400A.txt
lib/logitech_receiver/descriptors.py

device: remove incorrect feature for M325 mice

---

docs/devices/G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD 407C.text
docs/devices/G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD C33E.text
docs/devices/Wireless Mobile Mouse MX Anywhere 2S B01A.txt
lib/solaar/listener.py

defensive measures for lightspeed receiver

---

po/ca.po
po/cs.po
po/da.po
po/de.po
po/el.po
po/es.po
po/fi.po
po/fr.po
po/hr.po
po/it.po
po/ja.po
po/nb.po
po/nl.po
po/nn.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/sk.po
po/solaar.pot
po/sr.po
po/sv.po
po/tr.po

I have completed the Spanish translation and completed with some missing sentences.

Spanish translation reviewed (for 1.1.10-24)

---

lib/logitech_receiver/diversion.py
lib/solaar/cli/show.py

Fixes #2225
Addresses #2222
Also write empty file if there are no rules to save.

cli: be defensive in device error message

---

docs/installation.md

location was changed in 
https://github.com/pwr-Solaar/Solaar/commit/cf71736920ff85e9f5a082d3a7cfaadfc00af13d

Update installation.md with new udev rules location

---

lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/show.py
lib/solaar/ui/window.py

support extended report rate feature

---

po/ru.po
po/solaar.pot

To see real changes - see last commit. Firsts commits are just to format file, otherwise it was hard to see changes with all those "spaces" changes.
Also, fixes #2192.

Update RU language translation

---

lib/logitech_receiver/descriptors.py

device: override name of Candy Companion Chip

---

lib/solaar/cli/show.py

cli: no numbers for USB and Bluetooth devices

---

lib/logitech_receiver/settings_templates.py
lib/solaar/cli/show.py
lib/solaar/ui/config_panel.py

better handling of illegal setting values

---

Makefile
docs/installation.md

Simplify installation of udev rules

---

lib/solaar/ui/about.py

Fix invalid func name set logo name

---

.github/workflows/tests.yml

Remove dbus from macos dependencies

---

tests/logitech_receiver/test_common.py
tests/test_solaar.py

Introduces unit tests for Solaar.
Related #1097

Add tests of common module

---

.github/workflows/tests.yml
setup.py

Show pytest coverage in GitHub CI tests

---

lib/logitech_receiver/hidpp20.py

Clean up implementation of HID++ 2.0 feature_array.

clean up features array code

---

lib/hidapi/udev.py

hidapi: upgrade debugging in udev

---

README.md

Added link to Debian package and mention its maintainer. Also i removed mention about ubuntu version since they always changes b/c of "end of life/support". And i removed mention about kububntu since there are many other flavours of ubuntu like xubuntu.

Add link to Debian package to README.md

---

lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/pair_window.py

fix: Replace invalid hidpp10 usage

---

lib/logitech_receiver/receiver.py

refactor receiver using subclasses

---

Makefile
lib/logitech_receiver/base.py
tests/logitech_receiver/test_base.py

test: Test base product information

---

lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/hidpp10_constants.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py
lib/solaar/cli/show.py

receiver: delay device sending first messages

---

docs/usage.md

docs: document battery-icons=solaar option

---

lib/hidapi/hidconsole.py
lib/logitech_receiver/base.py
lib/logitech_receiver/common.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/diversion.py
lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/hidpp20_constants.py
lib/logitech_receiver/listener.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py
lib/solaar/cli/__init__.py
lib/solaar/cli/config.py
lib/solaar/cli/pair.py
lib/solaar/cli/probe.py
lib/solaar/cli/profiles.py
lib/solaar/cli/show.py
lib/solaar/cli/unpair.py
lib/solaar/gtk.py
lib/solaar/listener.py
lib/solaar/ui/diversion_rules.py
lib/solaar/ui/pair_window.py
lib/solaar/ui/tray.py
lib/solaar/ui/window.py

Used flynt to convert strings to f-strings, where safely possible.
Related #2372

Automatically upgrade strings to f-string

---

lib/logitech_receiver/common.py
lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py

allow sub-second delays in Later rule action

---

lib/hidapi/udev.py
lib/solaar/ui/__init__.py
lib/solaar/ui/action.py
lib/solaar/ui/config_panel.py
lib/solaar/ui/diversion_rules.py
lib/solaar/ui/icons.py
lib/solaar/ui/pair_window.py
lib/solaar/ui/rule_actions.py
lib/solaar/ui/rule_conditions.py
lib/solaar/ui/tray.py
lib/solaar/ui/window.py

Reduce deprecation warnings, mostly from Gtk.
They are mostly gone now.  One exception is due to some code in a package that Solaar uses.

ui: reduce deprecation warnings

---

lib/hidapi/udev.py
lib/logitech_receiver/common.py
lib/logitech_receiver/device.py
lib/logitech_receiver/diversion.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/__init__.py
lib/solaar/cli/pair.py
lib/solaar/cli/show.py
lib/solaar/cli/unpair.py
lib/solaar/ui/icons.py
lib/solaar/ui/window.py

Upgrade some more strings to fstring

---

lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp20.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/ui/config_panel.py
tests/logitech_receiver/hidpp.py
tests/logitech_receiver/test_hidpp20_complex.py
tests/logitech_receiver/test_setting_templates.py

implement and test BRIGHTNESS_CONTROL and RGB_EFFECTS

---

lib/logitech_receiver/receiver.py
lib/solaar/ui/pair_window.py
tests/solaar/ui/test_pair_window.py

improve pairing code

---

docs/capabilities.md
lib/logitech_receiver/common.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py
tests/logitech_receiver/hidpp.py
tests/logitech_receiver/test_setting_templates.py

implement and test per-key lighting

---

po/el.po

Hi
i just updated the greek translation inform me if any issues occur thanks

Updated  Greek Translation

---

docs/devices/G502 Lightspeed Wireless Gaming Mouse 407F.txt
docs/devices/G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD 407C.text
lib/logitech_receiver/device.py
lib/logitech_receiver/settings_templates.py
tests/logitech_receiver/test_device.py

device: initialize device registers to empty list

---

setup.py

dist: add included hid_parser to packages installed

---

po/zh_TW.po

Just sync the po file with the current solaar.pot and update some translations.

po: Update zh_TW Traditional Chinese translation

---

lib/logitech_receiver/diversion.py
lib/solaar/ui/diversion_rules.py
tests/logitech_receiver/test_diversion.py

Introduce tests for YAML rule loading functionality.
Related #2453

Refactor rule loading for testability

---

po/fr.po

Update French translation (for release 1.1.12)

---

lib/hidapi/hidconsole.py

input prompt: Remove Python 2 compatibility

---

lib/logitech_receiver/settings_templates.py
lib/logitech_receiver/special_keys.py
tests/logitech_receiver/test_setting_templates.py

settings: add and initialize per-key lighting to a special no-change value

---

lib/logitech_receiver/settings_templates.py
lib/solaar/listener.py
lib/solaar/ui/about.py
tests/logitech_receiver/test_setting_templates.py

get and use current host in K375sFnSwap to work around bug in MX Keys S firmware

---

lib/logitech_receiver/settings_templates.py
lib/solaar/dbus.py

add choices universe for backlight setting; fix bug in suspend and resume callback

---

po/fr.po
po/solaar.pot

- by David Geiger david.david@mageialinux-online.org

Update French translation (for release 1.1.13)

---

lib/hidapi/__init__.py
lib/hidapi/hidapi.py
lib/hidapi/hidconsole.py
lib/hidapi/udev.py

Remove all 'import xyz as _xyz' and favor import of module name to get more context in the code.
Related #2273

Unify imports in hidapi package

---

docs/rules.md

Allow users to find relevant information without reading a long wall of text.
Related #2497

Add headings to structure rules.md

---

docs/rules.md

- Page heading
- Fix heading levels
- Improve some names
Related #2497

Improve rules documentation

---

lib/logitech_receiver/base_usb.py
lib/logitech_receiver/descriptors.py
lib/logitech_receiver/device.py
lib/logitech_receiver/hidpp10.py
lib/logitech_receiver/hidpp10_constants.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py
lib/logitech_receiver/settings.py
lib/logitech_receiver/settings_templates.py
lib/solaar/cli/pair.py
lib/solaar/cli/probe.py
lib/solaar/listener.py
tests/logitech_receiver/test_hidpp10.py

Convert definition of HID registers to enum

---

setup.py

Automate handling of internal packages.
Related #2273

setup: Automatically find the packages in lib

---

lib/hidapi/udev.py
lib/logitech_receiver/base.py
lib/logitech_receiver/base_usb.py
lib/logitech_receiver/common.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/receiver.py

Clean up logitech receiver package

---

lib/solaar/cli/show.py

cli: finish change to show.py for new constants

---

lib/hidapi/udev.py

hidapi: remove check on driver

---

lib/logitech_receiver/settings_templates.py

settings: finish change to new constants

---

README.md
docs/index.md

docs: fix broken links to Solaar logo

---

lib/logitech_receiver/hidpp20.py

device: handle unknown device kinds

---

lib/logitech_receiver/base.py
lib/logitech_receiver/hidpp20.py

Fixes #2589
Also cycle sw_id instead of randomize

handle error return from root feature

---

lib/logitech_receiver/diversion.py

settings: allow unknown keys in Key rule conditions

---

tests/hid_parser/test_data.py

Add basic tests to cover the package.

Introduce hid_parser tests

---

lib/logitech_receiver/settings_templates.py

settings: check all bits for extended report rate

---

lib/solaar/ui/config_panel.py

ui: fix initialization bug for PackedRangeControl

---

lib/logitech_receiver/hidpp10_constants.py
lib/logitech_receiver/notifications.py
tests/logitech_receiver/test_base.py
tests/logitech_receiver/test_notifications.py

Replace some historic NamedInts enum for standard IntEnum

refactoring(logitech_receiver/notifications): change to intenums some NamedInts Errors

---

po/nb.po

Should be a pretty straight forward update of the po-file.

i18n: Updated Norwegian Bokmål (nb)

---

lib/logitech_receiver/settings_templates.py

fixes #2679
Please review carefully as I don't have much clue about this project.

Add ratchet setting for smart shift enhanced devices

---

bin/solaar

Remove Python 2 specific path handling

---

lib/logitech_receiver/base.py
tests/logitech_receiver/test_base.py

Use more appropriate function names and simplify code
Related #2273

Refactor device filter

---

lib/logitech_receiver/diversion.py

diversion: replace spaces by underscores when looking up features

---

lib/logitech_receiver/device.py
lib/solaar/ui/config_panel.py
tests/logitech_receiver/test_setting_templates.py

device: recover from errors in ping

---

lib/solaar/listener.py

ui: give ghost devices a path

---

lib/solaar/ui/diversion_rules.py

ui: correctly handle selection of [empty] in rule editor

---

lib/logitech_receiver/hidpp10_constants.py
lib/logitech_receiver/receiver.py
tests/logitech_receiver/test_receiver.py

Ensure functionality via unit test.

receiver: Handle unknown power switch locations again

---

docs/unistallation.md
mkdocs.yml

Changes made:  
1. Created a new `uninstallation.md` page.  
2. Updated `mkdocs.yml` to include the new page.

Adding uninstallation docs

---

lib/solaar/cli/__init__.py

cli: fix crash when asking for help about config

---

lib/logitech_receiver/settings_templates.py

settings: use correct LOD values for extended adjustable dpi

---

lib/logitech_receiver/hidpp10_constants.py
lib/solaar/cli/pair.py
lib/solaar/cli/show.py

hidpp10 constants NOTIFICATION_FLAG to NotificationFlag and DEVICE_FEATURES to DeviceFeature transition were incomplete.
Fixes solaar show and pair.
Closes #2852

fix flags in show and pair

---

lib/logitech_receiver/device.py
lib/logitech_receiver/notifications.py
lib/logitech_receiver/settings_templates.py
tests/logitech_receiver/fake_hidpp.py
tests/logitech_receiver/test_setting_templates.py

device: handle devices that turn off and on while still being pingable; use ADC feature to signal connection and disconnection

---

share/solaar/io.github.pwr_solaar.solaar.metainfo.xml

cf. https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines#url

docs(metainfo): Add link to source repo

---

lib/logitech_receiver/special_keys.py

device: add shape keys from Key POP Icon
